ccao-data/data-architecture

- .github/workflows/lint.yaml
- .jscpd.json
- .yamllint.yml
- dbt/dbt_project.yml
- dbt/models/default/schema.yml
- dbt/models/location/schema.yml
Our superlinter checks [are failing on the master branch](https://github.com/ccao-data/data-architecture/actions/runs/5684699106/job/15407982040) but they [passed on the most recent PR](https://github.com/ccao-data/data-architecture/actions/runs/5684620829/job/15407722505) (#23) because the config points to the wrong name for our main branch:
https://github.com/ccao-data/data-architecture/blob/72bf150a8eb4117191f4a84053527c60ae5f8818/.github/workflows/lint.yaml#L30
``` 
2023-07-27 19:23:43 [INFO]   Gathering user validation information...
2023-07-27 19:23:43 [INFO]   - Only validating [new], or [edited] files in code base...
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.
git pull <remote> <branch>
fatal: ambiguous …
```
> Fix superlinter on the master branch and ensure it runs on PRs

- aws-athena/views/default-vw_pin_condo_char.sql
Need to allow nonvliable.flag to be null as well as != 'questionable'
> Fix parking space flag handling of nonvlivable table

- aws-athena/views/sale-vw_ias_salesval_upload.sql
- dbt/dbt_project.yml
- dbt/models/sale/docs.md
- dbt/models/sale/sale.vw_ias_salesval_upload.sql
- dbt/models/sale/schema.yml
I've added a view based on discussions with @dfsnow to help with the iasworld sales table upload. I tried to follow [this template](https://github.com/ccao-data/data-architecture/blob/master/.github/ISSUE_TEMPLATE/new-dbt-model.md) as best as I could. Let me know what needs fixing! @jeancochrane.
Closes #146
> Add view for iasworld sales val join

- dbt/models/sale/docs.md
- dbt/models/sale/schema.yml
Adding three extra sources from the sales val program.
Closes #161.
> 161 add sales val tables to dbt schema file

- aws-glue/jobs/reporting-ratio_stats.py
Reverts ccao-data/data-architecture#160
> Revert "Remove pandas index from glue job output"

- aws-athena/views/location-vw_pin10_location_fill.sql
See https://github.com/ccao-data/data-architecture/issues/185
> Add tax school districts

- aws-s3/scripts-ccao-data-raw-us-east-1/sale-mydec.R
- aws-s3/scripts-ccao-data-warehouse-us-east-1/spatial-environment.R
see https://github.com/ccao-data/data-architecture/issues/220
> Remove 2015 Lake Michigan coastline artifacts

- dbt/models/default/schema/default.vw_pin_sale.yml
Simple PR to improve a single line of text.
> Improve dbt docs column description language

- aws-athena/ctas/proximity-dist_pin_to_airport.sql
- dbt/models/proximity/columns.md
- dbt/models/proximity/docs.md
- dbt/models/proximity/proximity.dist_pin_to_airport.sql
- dbt/models/proximity/schema.yml
Create SQL query for table that includes distance from O'Hare, distance from Midway, estimated DNL additions from each airport, and estimated total DNL (including baseline) for each airport. Update docs to include new model and new columns.
> Put proximity-dist_pin_to_airport table into dbt

- .github/workflows/build_and_test_dbt.yaml
- dbt/models/model/schema.yml
I forgot we have a workflow to build models every morning. Moved the materialization of `model` views to that workflow for simplicity.
> Materialize model views daily

- aws-athena/ctas/proximity-crosswalk_year_fill.sql
- aws-athena/views/model-vw_card_res_input.sql
- aws-athena/views/model-vw_pin_shared_input.sql
- aws-athena/views/proximity-vw_pin10_proximity.sql
- aws-athena/views/proximity-vw_pin10_proximity_fill.sql
- dbt/models/model/schema.yml
- dbt/models/proximity/columns.md
- dbt/models/proximity/schema.yml
@wagnerlmichael recently calculated distances to secondary roads. This PR incorporates those distances into our proximity and modeling views.
> Add secondary road to proximity and model views

- .github/actions/install_dbt_requirements/action.yaml
- dbt/models/sale/schema.yml
Adds a couple simple tests for the sales val pipeline.
> Add dbt tests to sale model

- aws-athena/ctas/proximity-crosswalk_year_fill.sql
- aws-athena/ctas/proximity-dist_pin_to_university.sql
- aws-athena/views/model-vw_card_res_input.sql
- aws-athena/views/model-vw_pin_shared_input.sql
- aws-athena/views/proximity-vw_pin10_proximity.sql
- aws-athena/views/proximity-vw_pin10_proximity_fill.sql
- dbt/models/proximity/columns.md
- dbt/models/proximity/docs.md
- dbt/models/proximity/proximity.dist_pin_to_university.sql
- dbt/models/proximity/schema.yml
This adds the distances between parcels and the following universities in feet
'Illinois Institute of Technology Chicago-Kent College of Law', 
'Columbia College', 
'University of Illinois at Chicago College of Medicine',
'Rush University Medical Center', 
'University of Chicago' 
'University of Illinois at Chicago',
'Northwestern University',
'Loyola University of Chicago',
'De Paul University', 
'Chicago State University', 
'Moraine Valley Community College'
> Add distance to major university

- aws-s3/scripts-ccao-data-warehouse-us-east-1/spatial-school.R
See https://github.com/ccao-data/data-architecture/issues/305.
> Linting and fix 17/18 missing cps boundaries

- dbt/models/model/schema.yml
- dbt/models/shared_columns.md
These columns are missing descriptions in dbt. Also need to fix the description for ccao_is_corner_lot.
> Add `is_active_exe_homeowner`, `n_years_exe_homeowner`, `airport_dnl_total` to dbt

- aws-athena/views/default-vw_pin_history.sql
Let's update our [Open Data - Assessed Values](https://github.com/ccao-data/wiki/blob/master/SOPs/Open-Data.md#assessed-values) data publication to have neighborhood code. This is a frequently requested filter by our power users.
>  Add nbhd code to Open Data - Assessed Values

- dbt/models/default/default.vw_pin_history.sql
See https://github.com/ccao-data/data-architecture/issues/483#issuecomment-2145493865
> QC Open Data, Assessed Values: PINs without townships

- dbt/models/default/default.vw_pin_universe.sql
- dbt/models/location/location.census_acs5.sql
- etl/scripts-ccao-data-warehouse-us-east-1/census/census-acs.R
- etl/scripts-ccao-data-warehouse-us-east-1/spatial/spatial-census.R
Just a quick addition of some columns in `vw_pin_universe` that are functions of pre-existing columns.
> Add fed and state congressional district nums

- dbt/models/default/schema/default.vw_pin_condo_char.yml
- dbt/models/reporting/docs.md
- dbt/models/reporting/reporting.vw_pin_value_long.sql
- dbt/models/reporting/schema.yml
Quick PR to add market value columns from `asmt_all` to the long version of `vw_pin_value`.
> Add MV to `reporting.vw_pin_value_long`

- dbt/models/default/default.vw_pin_land.sql
See https://github.com/ccao-data/data-architecture/issues/526
> Update aggregated land view with `allocpct` column

- dbt/models/reporting/schema.yml
Update https://github.com/ccao-data/data-architecture/pull/533 with [additional suggestion](https://github.com/ccao-data/data-architecture/pull/533#discussion_r1678306192).
>  Adjust exempt parcels with non-zero AV test

- etl/renv.lock
- etl/scripts-ccao-data-warehouse-us-east-1/ccao/ccao-commercial_valuation.R
Updates to commercial valuation data:
- consolidated columns previously prefixed with years
- added `subclass2`: Property type/use (2024 and later)
- added `totallandval`: Total land value
- added `model`: Commercial valuation modeling group
- added `townregion`: Township region
- updated description for `property_type/use`: Property type/use (2023 and before)
> 2024 commercial valuation ingest

- dbt/models/model/model.vw_pin_shared_input.sql
This PR implements the easiest incremental step for for resolving our [sporadically failing daily dbt model builds](https://github.com/ccao-data/data-architecture/actions/runs/12068826927/job/33654774064): Materializing the `model.vw_pin_shared_input` view. This view is queried by two of the most expensive model queries in the daily build (`model.vw_pin_condo_input` and `model.vw_card_res_input`), one of which is the culprit for sporadic failures. By materializing the output of the view, we expect to reduce overall resource usage in the daily build.
Evidence that these changes work: https://github.com/ccao-data/data-architecture/actions/runs/12188851207/job/34002787866#step:8:56
> Materialize `model.vw_pin_shared_input` view to speed up daily dbt builds

- dbt/README.md
- dbt/pyproject.toml
This PR updates our dbt project to use the latest version of dbt 1.9.
See the [release announcement](https://docs.getdbt.com/docs/dbt-versions/core-upgrade/upgrading-to-v1.9#new-and-changed-features-and-functionality) for an overview of changes, and see the [changelog](https://github.com/dbt-labs/dbt-core/blob/1.9.latest/CHANGELOG.md#dbt-core-190---december-09-2024) for a full list. Most of these changes are not relevant to our project, since 1.9 is focused primarily on improving snapshots and incremental models, neither of which we use in our project.
> Upgrade to dbt 1.9

- socrata/socrata_upload.py
Tiny formatting tweak to make output a little more readable.
> Improve Socrata API upload log formatting

- etl/scripts-ccao-data-warehouse-us-east-1/spatial/spatial-other.R
- etl/scripts-ccao-data-warehouse-us-east-1/spatial/spatial-school.R
Two minor changes in our etl. One was an error that would break the script, and one is a QoL improvement that is more in line with our current conventions for missing data.
> Fix a couple minor ETL oddities

- dbt/models/open_data/open_data.vw_sf_mf_improvement_char.sql
@jeancochrane you were so close to saving me from myself. I did mean to get rid of `char_recent_renovation` in the previous pull request, but not `char_renovation`.
> Revert char_renovation change

- dbt/models/reporting/reporting.ratio_stats.py
Adds med_ratio_met column referencing the new function in assesspy
Adds a  "Vertical Equity met" column; if either PRB or PRD is met, then true, else false.
Adds a column of sales_excluded_n
> Add new features to ratio stats

- dbt/models/open_data/open_data.vw_permit.sql
Quick PR to align `open_data.vw_permit` columns with our open data asset.
> Simplify address columns in permits open data asset

- dbt/models/open_data/exposures.yml
Quick PR to update an exposure label.
> Update Current Year Only asset label

- .github/workflows/socrata_upload.yaml
- socrata/socrata_upload.py
The job did [run as scheduled](https://github.com/ccao-data/data-architecture/actions/runs/13815182863/job/38646411048) without throwing an error, but didn't seem to do anything. I'm just trying to make it easier to figure out what went wrong here since I can't seem to replicate the issue locally.
> Add more printing to socrata API script

- .github/workflows/socrata_upload.yaml
See title. We got it this time, I can feel it.
> Set socrata workflow token length to 4 hours

- dbt/seeds/ccao/ccao.person.csv
This PR adds @SiennaWang12 to the `ccao.person` seed so that her name can be included in the list of names we use for random identifier generation. Thanks for your excellent work, Sienna!
Connects ccao-data/people#21.
> Add Sienna to `ccao.person`

- dbt/models/pinval/pinval.vw_assessment_card.sql
Add a municipality column ref for downstream pinval outputs.
Connects https://github.com/ccao-data/pinval/pull/92
> Add `loc_property_city` to `pinval.vw_assessment_card`

- dbt/seeds/pinval/pinval.model_run.csv
Per our testing, this run produces more intuitive results.
> Update `pinval.model_run` to switch to new run for 2025
