ccao-data/data-architecture

aws-athena/views/default-vw_pin_sale.sql

It seems like `vw_pin_sale` is missing a column in the `mydec_sales` subquery, causing dbt to raise this error when attempting to build the models:
```
18:53:31  Runtime Error in model vw_pin_sale_test (models/default/vw_pin_sale_test.sql)
18:53:31    line 212:18: Column 'mydec_sales.year_of_sale' cannot be resolved
```
This isn't a problem in the production Athena view, so this probably represents a discrepancy caused by drift between the prod view definition and the view definition stored in this repo. This PR updates the view definition in this repo to correctly select `year_of_sale` when generating the `mydec_sales` subquery.

Add missing year_of_sale column to mydec_sales subquery in vw_pin_sale

---

aws-athena/views/default-vw_pin_sale.sql
dbt/models/default/schema.yml
dbt/models/location/schema.yml

We know there are some existing integrity issues with our data that the data catalog is designed to help us address, but we don't want our dbt tests to unnecessarily alert us about these known issues while we're developing the catalog. To handle this problem, this PR adds some simple thresholds to the tests to ensure that they only fail when the number of test failures exceeds the number of expected failures.
The numbers used in these thresholds may not accurately reflect underlying integrity issues, and instead may simply represent problems with the tests themselves; we haven't thoroughly audited our tests yet so we can't rule that out. But I'm considering that effort out of scope for now, and will instead be a part of https://github.com/ccao-data/data-architecture/issues/27.
Adding …

Support incremental testing of dbt models through failure thresholds

---

.pre-commit-config.yaml
dbt/.sqlfluff
dbt/macros/generate_schema_name.sql
dbt/macros/slugify.sql
dbt/macros/tests/test_all.sql
dbt/macros/tests/test_generate_schema_name.sql
dbt/macros/tests/test_slugify.sql
dbt/macros/tests/utils.sql
dbt/tests/generic/test_column_length.sql
dbt/tests/generic/test_count_is_consistent.sql
dbt/tests/generic/test_no_extra_whitespace.sql
dbt/tests/generic/test_unique_combination_of_columns.sql

This PR sets up a pre-commit hook for [sqlfmt](https://docs.sqlfmt.com/) so that we can autoformat our dbt files and check for consistency on CI. It also runs sqlfmt autoformatting on all of our existing dbt files except our models, to which we are currently attempting to minimize edits as we build out the data catalog on the `data-catalog` branch.
Closes #30.

Add sqlfmt pre-commit hook for autoformatting dbt files

---

.github/actions/configure_dbt_environment/action.yaml

The `cleanup-dbt-resources` workflow is [currently failing](https://github.com/ccao-data/data-architecture/actions/runs/5801014337/job/15724340945) on the `data-catalog` branch because `GITHUB_REF_NAME` appears to be set to `data-catalog` even though the workflow is triggered from a `pull_request` event:
> Deleting the following schemas from Athena:
>
> "ci_data-catalog_default"
> "ci_data-catalog_location"
>
> An error occurred (EntityNotFoundException) when calling the DeleteDatabase operation: Database ci_data-catalog_default not found.
This PR adjusts the `configure-dbt-environment` action to give higher priority to environments that have `GITHUB_HEAD_REF` set when setting the `HEAD_REF` variable for a pull request, since this variable is guaranteed to only be set on `pull_request` …

Fix cleanup-dbt-resources workflow to run on data-catalog branch

---

dbt/README.md
dbt/models/default/schema.yml
dbt/tests/generic/test_expression_is_true.sql

In the process of producing a list of failing dbt tests along with queries to help investigate them (https://github.com/ccao-data/data-architecture/issues/60), I realized that tests that build on the `dbt_utils.expression_is_true` generic test are hard to debug because they don't select the columns relevant to the expression by default. This PR defines our own `expression_is_true` generic test that allows us to configure a `select_columns` attribute to select relevant columns when constructing the test query.
See [this comment](https://github.com/ccao-data/data-architecture/pull/63#issuecomment-1673366467) for a detailed explanation of the effect of this change, including example queries.
The PR also adds a brief section to the README explaining the process for editing and running queries …

Tweak failing dbt tests to make them easier to debug

---

.github/workflows/build_and_test_dbt.yaml
.github/workflows/deploy_dbt_docs.yaml

Three problems that emerged out of merging the data catalog branch into master (#78):
1. [Docs are not deploying](https://github.com/ccao-data/data-architecture/actions/runs/5905883640/job/16020814093) because we neglected to set up environment variables properly for the prod context
2. [Updating the dbt cache can fail](https://github.com/ccao-data/data-architecture/actions/runs/5906036003/job/16021252615) due to a naive `mv` call that is not actually performing the correct directory renaming
3. `$MODIFIED_RESOURCES_ONLY` [can be set to `false`](https://github.com/ccao-data/data-architecture/actions/runs/5906092110/job/16021431024) when we want it to be `true` in cases where we have to restore the cache from the `restore-keys` fallback
This PR fixes those three problems.

Fix dbt production deploy problems

---

.github/actions/setup_dbt/action.yaml
.github/workflows/build_and_test_dbt.yaml
.github/workflows/cleanup_dbt_resources.yaml
.github/workflows/deploy_dbt_docs.yaml
.github/workflows/test_dbt_models.yaml
.github/workflows/test_dbt_source_freshness.yaml
dbt/models/iasworld/schema.yml

This PR implements [source freshness checks](https://docs.getdbt.com/reference/commands/source#dbt-source-freshness) for our data catalog and initializes the checks with tests for three iasWorld tables (`htpar`, `asmt_all`, and `permit`). To run these checks, it adds a new CI workflow and schedules it to run at 9am CST every morning.
While adding the new workflow, I noticed that all of our dbt workflows currently share the same four setup steps. In the spirit of DRY, this PR also factors those steps out into a new `setup_dbt` composite action, and refactors the existing dbt workflows to use it.
Sample successful run [here](https://github.com/ccao-data/data-architecture/actions/runs/5931242660/job/16082679946?pr=84).
Closes https://github.com/ccao-data/data-architecture/issues/75.

Add new scheduled workflow to run source freshness checks every morning

---

dbt/macros/slugify.sql
dbt/macros/tests/test_slugify.sql

This PR updates our schema name generator so that schemas that start with numbers _are not_ prefixed with an underscore. The prefix underscore is designed to prevent invalid schemas (ones that start with numbers), but it is unnecessary for our use case since all dbt-generated schemas for non-main branches are prefixed with `dev_` or `ci_`.
Including the underscore prefix in the name generator results in schema names with repeated underscores when the feature branch is generated from an issue, i.e. `ci__70-create-reporting-view-with-most-recent-boundaries_census`.

Remove prefix underscore from slugified schema names

---

dbt/models/iasworld/docs.md
dbt/models/iasworld/schema.yml

Largely copied from the `dbt/models/default/schema.yml`.
I added the `docs.md` because the `schema.yaml` has the description field with a call to `doc()`. Let me know if I should keep that or not.
Each of the tests passed.

86 add uniqueness tests for iasworld tables

---

.github/workflows/deploy_dbt_docs.yaml

Dan noticed that the [Deployments view](https://github.com/ccao-data/data-architecture/deployments) for this repo isn't showing any successful docs deployments to GitHub Pages, despite the fact that we can see successful runs for the [`deploy-dbt-docs` workflow](https://github.com/ccao-data/data-architecture/actions/workflows/deploy_dbt_docs.yaml). Comparing this repo to [assesspy](https://github.com/ccao-data/assesspy), I noticed that we're missing an `environment` attribute in the `deploy-dbt-docs` workflow, which I suspect is the culprit.
```yaml
environment:
name: github-pages
url: ${{ steps.deployment.outputs.page_url }}
```
This PR adds an `environment` attribute to the `deploy-dbt-docs` workflow in order to get our Deployments view to show the correct status of our Pages …

Add deploy environment config to deploy_dbt_docs workflow

---

.github/actions/configure_dbt_environment/action.yaml
.github/actions/restore_dbt_cache/action.yaml
.github/actions/save_dbt_cache/action.yaml
.github/variables/dbt.env
.github/workflows/build_and_test_dbt.yaml

This PR adjusts the way that we store our dbt state caches to get around the fact that GitHub Actions caches cannot be updated once they've been created. By moving our state caches to S3, we can ensure that the cache always gets updated at the end of every successful run of the `build-and-test-dbt` workflow, which will allow subsequent runs to only build and test resources that have been modified since the last successful run.
See [this run](https://github.com/ccao-data/data-architecture/actions/runs/5968306499/job/16194026297) for evidence of the remote cache being used successfully.
Closes https://github.com/ccao-data/data-architecture/issues/89.

Move dbt cache to remote S3 storage

---

.github/workflows/deploy_dbt_docs.yaml
.gitignore
dbt/.gitignore
dbt/README.md
dbt/assets/dataflow-diagram.mmd
dbt/dbt_project.yml
dbt/models/overview.md

This PR initializes the overview section of our dbt docs with a new data flow diagram for our department's data.
You can check out the diagram on the [live docs site](https://ccao-data.github.io/data-architecture):
Closes https://github.com/ccao-data/wiki/issues/2. Connects https://github.com/ccao-data/data-architecture/issues/67.

Initialize data catalog overview docs with data flow diagram

---

.github/scripts/cleanup_dbt_resources.sh

This PR fixes a bug in the `cleanup-dbt-resources` workflow that causes it to fail in the (expected) case where it attempts to clean up a database that has not been created by CI. We adjust the underlying `cleanup_dbt_resources.sh` script to continue execution in cases where the `aws glue delete-database` command returns a nonzero status with `EntityNotFoundException` in the output.
Closes https://github.com/ccao-data/data-architecture/issues/104.
I tested this PR locally since it would be a bit of a pain to test on CI. I tested two cases:
1. **Sample output in the case of 404s**: I ran the script against the `dev` target without building any models, and confirmed that it completed execution
2. **Sample output in the case of unexpected error**: I adjusted the script to add a bogus …

Do not fail `cleanup-dbt-resources` workflow if databases do not exist

---

.github/scripts/cleanup_dbt_resources.sh

It turns out that https://github.com/ccao-data/data-architecture/issues/105 did not quite fix the issue described in #104. I had thought that `xargs` would continue execution and exit 0 if its subcommand returned a non-255 exit status, but it turns out that it continues execution and exits 123, which causes the workflow run to fail ([example](https://github.com/ccao-data/data-architecture/actions/runs/6026176207/job/16348510525#step:5:1)).
This PR adjusts the `EntityNotFoundException` conditional in `cleanup_dbt_resources.sh` so that we don't exit with a nonzero status in the case of a 404 response from the `aws glue delete-database` call.
Sample output demonstrating that this change works:
```console
(venv) jecochr@21CCAO-LAPTOP54:~/code/data-architecture/dbt$ …
```

Don't exit with a nonzero status when `delete-database` call returns 404 in cleanup workflow

---

.github/workflows/build_and_test_dbt.yaml
dbt/models/default/schema.yml

In Teams discussion with Nicole and Billy, I discovered two small problems with our `default.vw_card_res_char` tests:
1. `vw_card_res_char_unique_by_card_and_year` is incorrect, since this table is actually unique by card, year, and _PIN_
> [12:46 PM] Nicole Jardine (Assessor)
> I believe this view is unique to pin, year, and card
2. `vw_card_res_char_renovation_fields_match` is not actually useful, since it's just checking derived data, and the logic that generates these data is much more complicated than a simple test like "`char_renovation` should be the same value as `char_recent_renovation`"
> [1:40 PM] Jean Cochrane (Assessor)
>
> I'm wondering if the test checking whether `char_renovation` matches `char_recent_renovation` in `default.vw_card_res_char` needs some refinement... …

Fix `default.vw_card_res_char` tests to better match the reality of the view

---

.github/ISSUE_TEMPLATE/new-dbt-model.md
dbt/README.md

This PR updates `dbt/README.md` to add more detailed docs on how to develop our dbt catalog. These docs represent my best attempt at a full set of information that other developers in this office will need to effectively contribute to the data catalog.
As part of these docs, this PR also adds a new `Add a new dbt model` issue template that provides detailed instructions for how to add a new model, assuming no context on how our dbt setup works.
Closes #67 and https://github.com/ccao-data/data-architecture/issues/108.

Flesh out docs on how to develop our data catalog

---

aws-athena/views/default-vw_pin_condo_char.sql
aws-s3/renv.lock
aws-s3/scripts-ccao-data-raw-us-east-1/ccao-condominium_parking.R
aws-s3/scripts-ccao-data-warehouse-us-east-1/ccao-condominium_parking.R
dbt/models/ccao/schema.yml

@carolinedavidson discovered some condo units with negative predicted values in her condo report. We believe these units are likely non-livable and should be treated as such during modeling, reporting, etc.
This PR adds this data to ingest scripts (`ccao-condominium_parking.R`), generates an Athena table for the data, and adds it to the Athena condo characteristics view (`default.vw_pin_condo_char`).

114 add condo units with negative predicted values to declared livable/non livable spaces tables

---

dbt/models/default/schema.yml

A dbt test threshold caused a [major rebuild of the dbt DAG to fail](https://github.com/ccao-data/data-architecture/actions/runs/6191401587/job/16809768314). This is a fast follow to temporarily bump the test threshold so we can successfully build the DAG and cache its full state.

Bump address whitespace test failure threshold

---

.github/actions/configure_dbt_environment/action.yaml
.github/actions/restore_dbt_cache/action.yaml
.github/variables/dbt.env
.github/workflows/build_and_test_dbt.yaml
aws-athena/views/default-vw_pin_universe.sql

We've been seeing some intermittent build failures on CI due to the fact that we're attempting to defer to branch-specific state rather than master state on CI in some cases. (More details in #129.) This PR simplifies that logic by always deferring to master branch state on CI, which means that we will run more builds and tests than we otherwise would, but we will also experience a more stable CI pipeline.
I tested these changes a few different ways via temporary commits:
* See [this workflow run](https://github.com/ccao-data/data-architecture/actions/runs/6191129053/job/16808775960#step:8:1) for a test confirming that this deferral behavior works in a simple case where we modify `default.vw_pin_universe` and want to build/test it without building/testing its dependencies.
* See [this …

Always defer to master dbt state on CI to resolve intermittent build failures

---

aws-athena/ctas/location-access.sql
aws-athena/ctas/location-census.sql
aws-athena/ctas/location-census_acs5.sql
aws-athena/ctas/location-chicago.sql
aws-athena/ctas/location-crosswalk_year_fill.sql
aws-athena/ctas/location-economy.sql
aws-athena/ctas/location-environment.sql
aws-athena/ctas/location-other.sql
aws-athena/ctas/location-political.sql
aws-athena/ctas/location-school.sql
aws-athena/ctas/location-tax.sql
aws-athena/ctas/proximity-cnt_pin_num_bus_stop.sql
aws-athena/ctas/proximity-cnt_pin_num_foreclosure.sql
aws-athena/ctas/proximity-cnt_pin_num_school.sql
aws-athena/ctas/proximity-crosswalk_year_fill.sql
aws-athena/ctas/proximity-dist_pin_to_bike_trail.sql
aws-athena/ctas/proximity-dist_pin_to_cemetery.sql
aws-athena/ctas/proximity-dist_pin_to_cta_route.sql
aws-athena/ctas/proximity-dist_pin_to_cta_stop.sql
aws-athena/ctas/proximity-dist_pin_to_golf_course.sql
aws-athena/ctas/proximity-dist_pin_to_hospital.sql
aws-athena/ctas/proximity-dist_pin_to_lake_michigan.sql
aws-athena/ctas/proximity-dist_pin_to_major_road.sql
aws-athena/ctas/proximity-dist_pin_to_metra_route.sql
aws-athena/ctas/proximity-dist_pin_to_metra_stop.sql
aws-athena/ctas/proximity-dist_pin_to_park.sql
aws-athena/ctas/proximity-dist_pin_to_railroad.sql
aws-athena/ctas/proximity-dist_pin_to_water.sql

This PR implements a simple change that produces an absolutely horrendous diff: Removing the semantically-unnecessary CTAS subqueries that we introduced to make the diff in #111 simpler. The goal was to keep this PR as simple as possible, changing nothing except formatting, so that the reviewer can skim the diff and be confident that they won't miss anything important.
The diff is much easier to read if you enable the "hide whitespace" feature in the `Files changed` view:
Closes https://github.com/ccao-data/data-architecture/issues/120.

Remove unnecessary subqueries in CTAS models

---

dbt/.gitignore
dbt/README.md
dbt/profiles.yml
dbt/requirements.txt

The introduction of our spatial queries as materialized tables into the dbt DAG in https://github.com/ccao-data/data-architecture/pull/111 creates an additional layer of complexity for local dbt development, since the time to build the full DAG has increased from a couple of minutes to a couple of hours.
This PR updates the dbt README to provide detailed instructions on how to avoid building compute-intensive tables using [`dbt clone`](https://docs.getdbt.com/reference/commands/clone) and [the `--exclude` option](https://docs.getdbt.com/reference/node-selection/exclude). In order to support this workflow, we upgrade to the v1.6.x lines of dbt Core and the dbt-athena adapter, which are the first versions to support `dbt clone` in addition to being the latest stable minor versions of both …

Update dbt docs with more detail on handling table models and upgrade to dbt 1.6

---

dbt/models/default/schema.yml

The sqoop bot is [currently failing](https://github.com/ccao-data/data-architecture/actions/runs/6221555617) due to two tests, one for `vw_pin_appeal` and one for `vw_pin_sale`, that are failing due to a few extra rows of invalid data.
This PR bumps the failure thresholds for those tests since we don't yet have a set process for fixing these errors.

Bump thresholds for `vw_pin_appeal` and `vw_pin_sale` tests that are failing

---

.github/workflows/build_and_test_dbt.yaml

This PR adds a manual dispatch option for the `build-and-test-dbt` workflow. It takes a space-separated list of model names as an input, pulls the `master` branch cache, builds and tests the specified models, then re-uploads the cache to S3.
Closes #128.

Update build and test workflow with manual dispatch option

---

.github/ISSUE_TEMPLATE/new-dbt-model.md

The `new-dbt-model` issue template currently does not appear on the [New Issue page](https://github.com/ccao-data/data-architecture/issues/new/choose):
If you navigate to [the Markdown file](https://github.com/ccao-data/data-architecture/blob/master/.github/ISSUE_TEMPLATE/new-dbt-model.md), you'll notice GitHub displaying an error message saying `About can't be blank`:
This error message is not super clear, but comparing the template to a template that is successfully rendering in the New Issue view (`data-onboarding`) reveals the latter is using `about` instead of `description`, which seems related to the error message in question:
https://github.com/ccao-data/data-architecture/blob/4beab06c70d40c19c5932bfe8a4d6a7aeefe7001/.github/ISSUE_TEMPLATE/new-dbt-model.md?plain=1#L1-L5 …

Fix syntax error in `new-dbt-model` issue template so that it shows up in the New Issue view

---

.github/ISSUE_TEMPLATE/new-dbt-model.md

@wagnerlmichael noticed while following the instructions to add a new dbt model that the command for creating a new symlink resulted in a broken link due to path resolution problems. This PR tweaks those docs to ensure that we give readers a symlink command that will work.

Fix symlink instructions in new-dbt-model.md

---

dbt/README.md

This PR fixes the header links in the dbt README, which seem to be broken due to manual `<h2>` tags with `id` attributes not producing reliable links like I thought they did. I'm not sure if there has been a recent change to the GitHub rendering engine to make this trick not work anymore, or if it's just never worked the way I expect; but in this PR we remove the reliance on the `<h2>` tags and instead fall back to GitHub's autogenerated anchors. These anchors are ugly, and they have the downside of requiring that they be updated whenever header text changes, but they work nonetheless.
The changes in this PR can be tested by viewing the README file in this branch and clicking the links in the `Quick links` section: https://github.com/ccao-data/data-architecture/blob/jeancochrane/fix-links- …

Fix links in dbt README

---

.github/actions/publish_sns_topic/action.yaml
.github/scripts/test_open_data_assets.py
.github/workflows/test_dbt_models.yaml
.github/workflows/test_open_data_assets.yaml
dbt/macros/row_count_by_group.sql
dbt/macros/row_count_by_year.sql
dbt/models/default/schema.yml
dbt/models/proximity/schema.yml

This PR adds a new scheduled workflow `test-open-data-assets` that runs a Python script once a month to confirm that the row counts of our open data assets match the row counts of the views that produce them. The goal here is to create a system that can alert us if the Socrata agent is silently failing to publish rows for some data sets, which is behavior we've experienced in the past.
In order to implement this alerting system, this PR makes two major refactors:
* The logic that the `test-dbt-models` workflow uses to push failure notifications to SNS is factored out into a composite action, `publish_sns_topic`, so that it can be reused by the new workflow that runs open data tests.
* [Exposures](https://docs.getdbt.com/docs/build/exposures) are added to the dbt DAG for all of our open …

Add script and GitHub workflow to test open data assets on a schedule

---

aws-glue/jobs/reporting-ratio_stats.py

Lowering this limit allows us to report on geographies with few sales and as long as it's above 2 doesn't throw an error in glue.

Lower reporting minimum group sales threshold

---

aws-glue/jobs/reporting-ratio_stats.py

Minor PR to address accidental inclusion of pandas dataframe index in reporting.ratio_stats table.

Remove pandas index from glue job output

---

.github/ISSUE_TEMPLATE/new-dbt-model.md
dbt/README.md

In https://github.com/ccao-data/data-architecture/pull/164, we're moving to a new pattern where we only use doc blocks for descriptions if they're reused by >2 entities. This PR updates our guidance to ensure that this pattern is documented.

Update guidance on defining model descriptions

---

aws-athena/views/default-vw_pin_sale.sql

A single duplicate sale is created when we remove 'D' from the `instruno` column in `iasworld.sales`. Let's get rid of it.

Remove single duplicate sale from vw_pin_sale

---

aws-athena/views/default-vw_pin_sale.sql

This PR successfully joins (tested in dbt, view is on my dev database) the sales val data into `default.vw_pin_sale`. 
Outstanding questions:
- Column order
- What do we do with prior sale filter data
- Correct columns included
- Column names
Closes #97

Update view to contain sales val characteristics

---

aws-athena/views/default-vw_pin_sale.sql

Because there can be duplicates within pin and document number, we need to make the calculation of number of parcels associated with a sale invoke DISTINCT

Correct nopar calculation

---

aws-athena/views/default-vw_pin_sale.sql

The new `bad_doc_no` column was not sorted enough to avoid tiebreakers and was causing different row counts each time the view was queried.

Address randomness caused by athena tiebreak in bad_doc_no

---

aws-athena/views/default-legacy_vw_pin_sale.sql
aws-athena/views/reporting-vw_pin_most_recent_sale.sql
aws-athena/views/reporting-vw_ratio_stats.sql
aws-athena/views/reporting-vw_res_report_summary.sql
aws-athena/views/reporting-vw_town_sale_history.sql
dbt/models/default/default.legacy_vw_pin_sale.sql

We want to push out some pretty big changes to vw_pin_sale, but not disrupt reporting. Eventually reporting will incorporate the changes to vw_pin_sale, but for he next few weeks if we point reporting views at a legacy version of vw_pin_sale we can move forward with our changes and keep reporting consistent for the tri. Not a permanent solution.

Create legacy view, point reporting at legacy view

---

aws-athena/views/default-legacy_vw_pin_sale.sql

This PR drops the (unused) sales val model outputs from the temporary legacy sales view. The view is currently throwing the following error due to a change in the underlying datatype of the sales val output:
```
Failed analyzing stored view 'awsdatacatalog.reporting.vw_ratio_stats': line 79:8: View 
'awsdatacatalog.default.legacy_vw_pin_sale' is stale or in invalid state: column 
[sv_is_outlier] of type boolean projected from query view at position 45 cannot be coerced 
to column [sv_is_outlier] of type bigint stored in view definition
```
This error is blocking reporting jobs from running. Removing the sales val outputs and redefining the view should be a quick fix. Pinging @wrridgeway for awareness.

Drop sales val outputs from legacy sale view

---

dbt/models/default/schema/default.vw_pin_sale.yml
dbt/models/sale/docs.md
dbt/models/sale/schema.yml
dbt/models/shared_columns.md

This PR adds column documentation to all tables and views in the `sale` schema. It also adds top-level documentation to each table/view. Finally, it correctly capitalizes MyDec elsewhere in our dbt documentation.
@wagnerlmichael please review this for accuracy.

Add dbt documentation to `sale.*` assets

---

aws-s3/renv.lock

During the exploratory analysis in #195, we discovered that the `osmdata` package was out of date. The package update fixes the following error:
```
> osm_roads <- opq(bbox = "Cook County, IL") %>%
+   add_osm_feature(
+     key = "highway",
+     value = c("motorway", "trunk", "primary")
+   ) %>%
+   osmdata_sf() %>%
+   .$osm_lines %>%
+   select(osm_id, name) %>%
+   st_transform(4326) %>%
+   mutate(geometry_3435 = st_transform(geometry, 3435))
Error in `httr2::req_perform()`:
! HTTP 405 Method Not Allowed.
Run `rlang::last_trace()` to see where the error occurred.
```

Update osmdata package

---

dbt/dbt_project.yml

This PR updates the Parquet write compression used by all dbt materialized models. Swapping from the default `snappy` compression to `zstd` reduces data queried by Athena by 30-40%  with basically no loss in query performance.
> [!NOTE]
Let's merge this after working hours since it will temporarily bork critical tables.

Update CTAS write compression

---

dbt/assets/sales-lineage.mmd
dbt/models/default/docs.md

Got some additional notes on how sales data is imported into the various systems of record. I'm adding those notes to `default.vw_pin_sale` for posterity.

Add sales view lineage to docs

---

.github/actions/configure_dbt_environment/action.yaml

This PR adds a small tweak to detect and use PR context for dbt when using the `workflow_dispatch` option. The fix is needed because using `GITHUB_HEAD_REF` to detect PR context (and thus to set the dbt target to `ci`) doesn't work for manually dispatched workflows. The issue was discovered during these workflow runs:
- https://github.com/ccao-data/data-architecture/actions/runs/6804924433/job/18503445904
- https://github.com/ccao-data/data-architecture/actions/runs/6804785306/job/18503010735

Add `workflow_dispatch` fix for CI dbt builds

---

aws-athena/views/default-vw_pin_appeal.sql
dbt/models/default/schema/default.vw_pin_appeal.yml

Assuming this (`htpar.user104`) data won't get fixed anytime soon, addressing it in `default.vw_pin_appeal` seems to be our best bet for now.

Mitigate incorrect values in htpar.user104

---

aws-athena/views/default-vw_pin_sale.sql
dbt/models/default/schema/default.vw_pin_sale.yml

- update multisale detection to remove the letter 'D' from document number when tallying how many parcels are associated with a sale
- remove language about cards in mydec sales
- add mydec deed type to vw_pin_sale
- use mydec's number of parcels per sale column to exclude multisales before joining mydec data to iasworld.sales

Update multisale detection

---

aws-athena/views/default-vw_card_res_char.sql
aws-athena/views/default-vw_pin_address.sql
aws-athena/views/default-vw_pin_appeal.sql
aws-athena/views/default-vw_pin_exempt.sql
aws-athena/views/default-vw_pin_history.sql
aws-athena/views/default-vw_pin_sale.sql
aws-athena/views/default-vw_pin_universe.sql
aws-athena/views/model-vw_card_res_input.sql
aws-athena/views/model-vw_pin_condo_input.sql
aws-athena/views/model-vw_pin_shared_input.sql
dbt/models/default/schema/default.vw_card_res_char.yml
dbt/models/default/schema/default.vw_pin_address.yml
dbt/models/default/schema/default.vw_pin_appeal.yml
dbt/models/default/schema/default.vw_pin_exempt.yml
dbt/models/default/schema/default.vw_pin_history.yml
dbt/models/default/schema/default.vw_pin_sale.yml
dbt/models/default/schema/default.vw_pin_universe.yml
dbt/tests/generic/test_row_count.sql

PR #141 introduced a significant regression that resulted in incorrect row counts for important views. The regression primarily affected the experimental `default.vw_pin_appeal` view and resulted in over 90% of its values being missing. Other models break down like so:
| Database | Model               | Cur. Count | PR Count |   Diff. | Pct. Missing |
|----------|---------------------|-----------:|---------:|--------:|-------------:|
| default  | vw_card_res_char    |   27347262 | 27347262 |       0 |        0.00% |
| default  | vw_pin_address      |   45071159 | 45079937 |    8778 |        0.02% |
| default  | vw_pin_appeal       |     743601 |  8407667 | 7664066 |       91.16% |
| default  | vw_pin_exempt       |     184845 |   184845 |       0 |        0.00% |
| default  | …

Fix where clause logic to deactivate PINs

---

dbt/README.md

While pairing on dbt setup with Damon, I noticed a couple of outdated sections in the README. This PR tweaks those sections so that the setup instructions work as written.

Bring dbt setup instructions up to date

---

dbt/models/default/docs.md
dbt/models/iasworld/docs.md
dbt/models/shared_columns.md

We have learned that owner information has _not been regularly updated_ in owndat since 2017. This PR makes note of that in the dbt docs for `iasworld.owndat`, `default.vw_pin_address`, and `default.vw_pin_exempt`.

Update dbt docs with warnings about mailing address staleness

---

dbt/dbt_project.yml
dbt/models/default/schema/default.vw_card_res_char.yml
dbt/models/default/schema/default.vw_pin_address.yml
dbt/models/default/schema/default.vw_pin_appeal.yml
dbt/models/iasworld/schema/iasworld.addn.yml
dbt/models/iasworld/schema/iasworld.aprval.yml
dbt/models/iasworld/schema/iasworld.asmt_all.yml
dbt/models/iasworld/schema/iasworld.comdat.yml
dbt/models/iasworld/schema/iasworld.dweldat.yml
dbt/models/iasworld/schema/iasworld.htpar.yml
dbt/models/iasworld/schema/iasworld.land.yml
dbt/models/iasworld/schema/iasworld.legdat.yml
dbt/models/iasworld/schema/iasworld.oby.yml
dbt/models/iasworld/schema/iasworld.owndat.yml
dbt/models/iasworld/schema/iasworld.pardat.yml
dbt/models/qc/schema.yml

This PR adds a time filter to most `tag:test_qc*` dbt tests related to testing raw iasWorld data. Currently, it limits all tests to only the current year, as set in `dbt_project.yml`. This is because we can't actually correct errors from prior years in most cases, so they aren't worth actually testing.

Add time filter to QC tests

---

aws-athena/views/default-vw_pin_universe.sql
dbt/README.md
dbt/macros/generate_schema_name.sql
dbt/macros/tests/test_generate_schema_name.sql

This PR amends changes the prefixes used to identify non-prod databases in Athena. It changes:
- `dev_` -> `z_dev_`
- `ci_` -> `z_ci_`
This sorts all the non-prod databases to the bottom of the Athena dropdown menu (where they belong).
Successful run to create a prefixed DB here: https://github.com/ccao-data/data-architecture/actions/runs/7052325320/job/19197128258?pr=256
I also created a local `z_dev_` environment.

Prefix non-prod databases with `z_` for better sorting

---

aws-athena/views/model-vw_card_res_input.sql

I accidentally removed/moved this column when I needed to use it as a partition key in #232. This PR re-adds it to its proper place.

Re-add `meta_year` column to `model.vw_card_res_input`

---

dbt/profiles.yml

This PR changes the `dbt-test` test database name to `z_static_unused-dbt-stub-database` to make it more descriptive and aligned with the new sorting added in #256.

Change `dbt-test` database schema name

---

aws-athena/views/default-vw_pin_history.sql
aws-athena/views/default-vw_pin_value.sql
dbt/models/ccao/docs.md
dbt/models/default/schema/default.vw_pin_history.yml
dbt/models/default/schema/default.vw_pin_value.yml
dbt/models/iasworld/columns.md
dbt/models/iasworld/schema/iasworld.aprval.yml
dbt/models/shared_columns.md

The field `aprval.reascd` contains the reason codes for changes in assessed values. It is used heavily within Inquire queries to append the change code to any query that uses `ASMT_ALL`. We should update our views to include this column where appropriate, as well as create a `CASE WHEN` statement or table containing the human-readable change reasons.
Additionally, we should add the change reasons to the dbt documentation for this column.

 Add APRVAL.reascd field to default.vw_pin_value and dbt docs

---

.gitignore
aws-s3/scripts-ccao-data-raw-us-east-1/spatial-corner_lot.R

This PR consolidates the work done on the [`108-create-corner-lot-indicator` branch](https://github.com/ccao-data/data-architecture/tree/108-create-corner-lot-indicator) to merge the corner lots script into the main branch of this repo. It uses a fresh branch instead of `108-create-corner-lot-indicator` since that branch is very far behind the main branch and contains a bunch of files that we don't want to merge.

Add script to compute corner lots indicator

---

aws-s3/scripts-ccao-data-raw-us-east-1/spatial-corner_lot.R

I took a brief look at `aws-s3/scripts-ccao-data-raw-us-east-1/spatial-corner_lot.R` after merging #265 and realized that there were a couple of pieces of outdated info in the docstring. This tiny PR fixes that info to ensure that future users have the correct instructions on where output files will get generated and how to upload them to S3.
Note that I'm not 100% confident in where these files should live in S3; I originally had thought that `location.corner_lot` made the most sense, but then refactored to `spatial.corner_lot` after noticing that the [`108-create-corner-lot-indicator` branch](https://github.com/ccao-data/data-architecture/tree/108-create-corner-lot-indicator) had previously used the `spatial` prefix. I'm open to either location as long as it's consistent, so let me know …

Update docstring for `spatial-corner_lot.R`

---

.github/workflows/test_dbt_source_freshness.yaml

This PR updates the `test_dbt_source_freshness` workflow to publish a notification to the dbt testing SNS topic in case of failure. This behavior is only configured for scheduled runs, where GitHub will otherwise [notify the user who last edited the schedule](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule).
Workflow run testing the notification: https://github.com/ccao-data/data-architecture/actions/runs/7213700182/job/19654135786
Closes #269.

Update source freshness tests to publish to SNS on scheduled job failure

---

aws-athena/views/default-vw_pin_universe.sql
aws-athena/views/model-vw_card_res_input.sql
aws-athena/views/model-vw_pin_shared_input.sql
dbt/models/ccao/docs.md
dbt/models/ccao/schema.yml
dbt/models/default/schema/default.vw_pin_universe.yml
dbt/models/model/schema.yml
dbt/models/shared_columns.md

Corner lots live in `ccao.corner_lot` but have not been added to any of the views used for modelling. Let's add it to `default.vw_card_res_char` and `default.vw_pin_condo_char` so that we can use it in the modeling pipelines.

Add corner lot indicator to modeling views

---

.github/scripts/test_open_data_assets.py
dbt/models/default/exposures.yml

Open data asset tests are [currently failing](https://github.com/ccao-data/data-architecture/actions/runs/7398271855/job/20127082689) because we changed the name of the year field in the `Assessed Values` asset from `year` to `tax_year`:
```
requests.exceptions.HTTPError: 400 Client Error:
Bad Request for url: https://datacatalog.cookcountyil.gov/resource/uzyt-m557.json?%24query=SELECT+COUNT%28%2A%29%2Cyear+GROUP+BY+year
```
Here's the API response that's causing this 400 error:
```
{"message":"Query coordinator error: query.soql.no-such-column; No such column: year;
position: Map(row -> 1, column -> 238, line -> \"SELECT `pin`, `tax_year`, `class`, `township_code`,
`township_name`, `mailed_bldg`, `mailed_land`, `mailed_tot`, `certified_bldg`, `certified_land`, `certified_tot`, …
```

Allow configuring a custom `year_field` for open data asset tests

---

aws-athena/ctas/location-crosswalk_year_fill.sql
aws-athena/views/location-vw_pin10_location_fill.sql

'omp' is a value for `env_airport_noise_data_year` in our location data crosswalk, but can't be joined to our generic `year`column. Airport noise is already filled during ingest so we don't need to use `env_airport_noise_data_year` when joining data for `location.vw_pin10_fill`

Correct `env_airport_noise_data_year` fill misjoin

---

aws-athena/views/model-vw_card_res_input.sql
aws-athena/views/model-vw_pin_shared_input.sql

This PR adds two exemption-related features to the residential model input view:
1. Whether or not a PIN has an exemption active in a given year
2. How many consecutive years a PIN has had an exemption active

Add exemptions feature subquery/CTE

---

aws-athena/ctas/proximity-dist_pin_to_cta_route.sql
aws-athena/ctas/proximity-dist_pin_to_cta_stop.sql
aws-athena/ctas/proximity-dist_pin_to_metra_route.sql
aws-athena/ctas/proximity-dist_pin_to_metra_stop.sql
aws-athena/ctas/proximity-dist_pin_to_park.sql
aws-athena/ctas/proximity-dist_pin_to_university.sql
dbt/macros/dist_to_nearest_geometry.sql

Per @jeancochrane's example in #295, I've refactored the distance to nearest geometry macro to use a CTE instead of a conditional passed as a macro argument. This is significantly simpler and more intuitive in my opinion while getting the same results.

Move conditional for nearest dist macro to CTE

---

aws-athena/ctas/proximity-dist_pin_to_pin.sql
aws-athena/ctas/proximity-dist_pin_to_pin_01.sql
aws-athena/ctas/proximity-dist_pin_to_pin_02.sql
aws-athena/ctas/proximity-dist_pin_to_pin_03.sql
aws-athena/ctas/proximity-dist_pin_to_pin_10km.sql
dbt/macros/nearest_pin_neighbors.sql
dbt/models/proximity/docs.md
dbt/models/proximity/proximity.dist_pin_to_pin_01.sql
dbt/models/proximity/proximity.dist_pin_to_pin_02.sql
dbt/models/proximity/proximity.dist_pin_to_pin_03.sql
dbt/models/proximity/proximity.dist_pin_to_pin_10km.sql
dbt/models/proximity/proximity.dist_pin_to_pin_1km.sql
dbt/models/proximity/schema.yml

This PR fixes some subtle misbehavior in the PIN-to-PIN distance calculation CTAS queries.
`proximity.dist_pin_to_pin` contains occasional duplicate rows, such as PIN10 3120118009. This leads to duplicate rows in downstream views such as `proximity.vw_pin10_proximity` and the model views.
I initially thought the cause was somehow due to changing centroids over time. However, it seems that the duplicates are instead the result of some tricky anti-join behavior.
Let's look at 3120118009 as an example. This PIN *exists* in the results of the "first pass" CTAS with a buffer radius of 1km (`proximity.dist_pin_to_pin_1km`). However, it only has rows for 2004-2023 (even though the parcel data goes back to 2000). This is because prior to 2004, no PIN existed that was closer than 1km. Its nearest …

Fix duplicates in PIN proximity view

---

.github/scripts/format_dbt_test_failures.py
.github/scripts/format_dbt_test_failures_requirements.txt
dbt/.gitignore
dbt/models/iasworld/schema/iasworld.asmt_all.yml
dbt/models/iasworld/schema/iasworld.dweldat.yml
dbt/models/iasworld/schema/iasworld.htpar.yml
dbt/models/iasworld/schema/iasworld.land.yml
dbt/models/iasworld/schema/iasworld.legdat.yml
dbt/models/iasworld/schema/iasworld.oby.yml
dbt/models/iasworld/schema/iasworld.owndat.yml
dbt/models/qc/schema.yml

This PR makes a number of quality-of-life improvements to the dbt test workbook that gets output by the `.github/scripts/format_dbt_test_failures.py` script. It is the basis of the workbook that was sent over to the rest of the internal stakeholders for review.
Improvements include:
* Adds a test caching system to speed up workbook development
* Writes test results using a write-only openpyxl workbook in order to reduce memory use
* Adds groupings for worksheet columns, with dedicated colors and top-level headers
* Adds support for a new `test_qc_exclude_from_workbook` tag that can be used to exclude certain tests or models
* Adds a few missing descriptions and columns for failing tests
Changes were tested by generating the workbook with the following commands run in the `dbt/` …

Clean up and format dbt test workbook

---

aws-athena/views/default-vw_pin_condo_char.sql

See https://github.com/ccao-data/data-architecture/issues/309.
This seems like a better solution for the present then back/forward filling these chars since we only have one observation per pin. Once this data gets moved into iasworld we can start filling. Until then, this is probably more robust.

Test complete filling for collected condo chars

---

aws-athena/views/default-vw_pin_condo_char.sql

The `bldg_is_mixed_use` indicator in `default.vw_pin_condo_char` isn't currently detecting _any_ mixed use buildings. This is due to its design and a conditional in the `chars` section of the `default.vw_pin_condo_char` sql script:
```
COALESCE(SUM(
CASE
WHEN
par.class NOT IN ('299', '2-99', '399')
THEN 1
ELSE 0
END
)
OVER (
PARTITION BY SUBSTR(par.parid, 1, 10), par.taxyr
)
> 0, FALSE)
AS bldg_is_mixed_use
```
and `WHERE class IN ('299', '2-99', '399')`
We need to allow non-299/399 class parcels into this part of the pull in order to be able to detect mixed-use buildings. We can filter them out later. I've included output below to show that these buildings are now being detected and that the new syntax has not altered parcel counts or other features such as CDU.

Move class exclusion to `filled` pull

---

aws-athena/views/default-vw_pin_sale.sql
dbt/models/default/schema/default.vw_pin_sale.yml

Joining calculated number of sales currently uses an adjusted document number against an un-adjusted document number.

 Correctly join calculated number of parcels per sale to sales view

---

aws-athena/views/default-vw_pin_sale.sql
dbt/models/default/schema/default.vw_pin_sale.yml

There are 8 rows in `iasworld.sales` with `NULL` values for nopar that don't get properly handled during the construction of `is_multisale` in `default.vw_pin_sale`.

Address `NULL` values for `iasworld.sales.nopar` in construction of `default.vw_pin_sale.is_multisale`

---

.github/scripts/cleanup_dbt_resources.sh
dbt/seeds/location/schema.yml

This PR implements two small changes I neglected to include as part of https://github.com/ccao-data/data-architecture/pull/343:
1. Updating the `cleanup_dbt_resources` workflow so that it determines which staging schemas to delete based on seeds as well as models
2. Manually overriding the column type for `location.neighborhood_group.nbhd` so that it gets parsed as a string rather than an integer
Note that excluding change 1 from #343 didn't actually cause a bug in the cleanup behavior. Since the only seed we have in the project is currently stored under the `location` schema, and the `location` schema is shared with other models, the cleanup workflow successfully deleted the schema based on the existence of models under the `location` schema …

Update `cleanup_dbt_resources` for seeds and fix `location.neighborhood_group.nbhd` type

---

aws-glue/jobs/reporting-ratio_stats.py

Switching `geography_id` to string in [ratio_stats.py](https://github.com/ccao-data/data-architecture/blob/master/aws-glue/jobs/reporting-ratio_stats.py) would make reporting easier for @ccao-jardine

Change `geography_id` type to string in `ratio_stats.py`

---

dbt/models/iasworld/schema/iasworld.addn.yml
dbt/models/iasworld/schema/iasworld.aprval.yml
dbt/models/iasworld/schema/iasworld.asmt_all.yml
dbt/models/iasworld/schema/iasworld.comdat.yml
dbt/models/iasworld/schema/iasworld.dweldat.yml
dbt/models/iasworld/schema/iasworld.htagnt.yml
dbt/models/iasworld/schema/iasworld.htpar.yml
dbt/models/iasworld/schema/iasworld.land.yml
dbt/models/iasworld/schema/iasworld.legdat.yml
dbt/models/iasworld/schema/iasworld.oby.yml
dbt/models/iasworld/schema/iasworld.owndat.yml
dbt/models/iasworld/schema/iasworld.pardat.yml
dbt/models/iasworld/schema/iasworld.sales.yml
dbt/models/qc/schema.yml
dbt/tests/generic/test_sequential_values.sql

This PR adds `meta.description` and `additional_select_columns` attributes to all remaining dbt QC tests that are not fully configured following https://github.com/ccao-data/data-architecture/pull/281. This mostly represents non-failing tests, and I've confirmed via inspection of the workbook that the test output remains the same following this change. Note that since these attributes are only needed for outputting the QC test workbook, we only add them to tests that are configured with the `test_qc_*` tag and do not also have the `test_qc_exclude_from_workbook` tag, since these are the only tests that get output to the workbook.
Closes https://github.com/ccao-data/data-architecture/issues/344 and closes https://github.com/ccao-data/data-architecture/issues/263.

Add descriptions and selected columns for all non failing tests

---

dbt/package-lock.yml
dbt/requirements.txt

This PR upgrades the `dbt-athena-community` package (released by the https://github.com/dbt-athena/dbt-athena/ repo) from `1.6.4` to `1.7.1`, enabling support for the dbt `1.7.*` line.
Note that while `1.7.2` is [currently available](https://github.com/dbt-athena/dbt-athena/releases) for `dbt-athena-community`, I ran into a bug that is preventing it from working with our configuration (https://github.com/dbt-athena/dbt-athena/issues/607). For now, I'm pinning to the second-most recent version, since there don't seem to be any important bugfixes in `1.7.2` according to [the changelog](https://github.com/dbt-athena/dbt-athena/releases/tag/v1.7.2) and I want to unblock us on upgrading to dbt `1.7.*`. I'll upgrade again to `1.7.2` when https://github.com/dbt-athena/dbt-athena/issues/607 is …

Upgrade `dbt-athena-community` to `1.7.1`

---

dbt/macros/format_additional_select_columns.sql
dbt/models/tax/schema.yml
dbt/tests/generic/test_res_class_matches_pardat.sql
dbt/tests/generic/test_row_values_match_after_join.sql

We would like to use the `row_values_match_after_join` and `res_class_matches_pardat` generics to implement https://github.com/ccao-data/ptaxsim/issues/31, but the generics as they exist now are too rigid to support the kinds of joins we need to do in those tests. In particular, neither test currently supports base models whose `parid` and `taxyr` columns have different names (e.g. `pin` or `year`), and `row_values_match_after_join` doesn't support left or outer joins.
This PR makes some tweaks to the two generics to support base models whose name schemes do not include `parid` and `taxyr`, and adds a `join_type` parameter to `row_values_match_after_join`. The changes are backwards-compatible in the case of `res_class_matches_pardat`, but breaking in the case of …

Refactor `row_values_match_after_join` and `res_class_matches_pardat` for join flexibility

---

dbt/models/tax/schema.yml

This PR creates 3 of the 4 dbt tests requested in the following [issue ](https://github.com/ccao-data/ptaxsim/issues/31). The fourth is on hold, due to the fact that there are known valuation discrepancies between iasWorld and PTaxSim. Thus, we may want to include a buffer on the matching function.  
I can't link the issue in the development sections since it's in the PTaxSim repository.

Add class checks and other data validation prior to final db export

---

.github/workflows/test_dbt_models.yaml
dbt/models/tax/schema.yml
dbt/selectors.yml

This PR fixes a bug in the `test-dbt-models` workflow revealed by the [latest workflow run](https://github.com/ccao-data/data-architecture/actions/runs/8629528053/job/23653918137). The [indirect selection](https://docs.getdbt.com/reference/node-selection/test-selection-examples#indirect-selection) for our tests is set to "eager" by default, which means:
> By default, runs tests if any of the parent nodes are selected, regardless of whether all dependencies are met. This includes ANY tests that reference the selected nodes.
As a result, tests that are defined on a non-selected model will be run if they reference a selected model in an argument. This causes `test-dbt-models` to run `tax.pin` tests that reference `legdat` and `pardat` in their arguments: …

Add selector for `test-dbt-models` workflow and set its indirect selection to "cautious"

---

dbt/models/iasworld/schema/iasworld.pardat.yml

This test results in a failure with 3024 results.

Add new test to make sure tieback pins don't contain hyphens

---

.github/workflows/deploy_dbt_docs.yaml
dbt/assets/ccao-script.js

I got sufficiently annoyed with the dbt docs sidebar that I took a minute to tweak it. Here we:
- Remove the useless "Group" tab
- Open the "Database" tab and "awsdatacatalog" DB by default

Tweak dbt data docs sidebar

---

dbt/models/default/schema/default.vw_pin_sale.yml

We need to be sure our legacy sales filters are doing what is expected of them. This can be handled through dbt tests for `default.vw_pin_sale`.

Add dbt tests for sales view legacy filters

---

aws-s3/scripts-ccao-data-warehouse-us-east-1/spatial-census.R

`spatial.census` has `NULL` names for these two census district types.
This PR also removes `ZZZ` geoid state congressional districts.

 Fix missing names for state rep and state senate census districts

---

.github/scripts/transform_dbt_test_results.py
dbt/dbt_project.yml
dbt/models/default/schema/default.vw_pin_value.yml
dbt/models/iasworld/schema/iasworld.dweldat.yml
dbt/models/iasworld/schema/iasworld.land.yml
dbt/models/shared_columns.md
dbt/tests/generic/test_is_null.sql

This PR makes a number of small edits to our dbt tests as described in https://github.com/ccao-data/data-architecture/issues/371. See that issue for a full list of the changes.
There are a few changes from the list that I haven't made yet. I'm curious to get your take:
* Update `iasworld_oby_card_between_1_and_100` to exclude condos, and see if the results are accurate (i.e., make sure that there are no non-condo buildings where card >100 makes sense)
* These query results make me doubt that the failures are related to condos with large numbers of cards:
```sql
select oby.class, failures.*
from z_dev_jecochr_test_failure.iasworld_oby_card_between_1_and_100 failures
join iasworld.oby oby
on oby.parid = failures.parid
and oby.taxyr = failures.taxyr
and oby.cur = 'Y'
and oby.deactivat is …
```

Small edits to dbt tests based on feedback

---

.github/workflows/deploy_dbt_docs.yaml
dbt/models/iasworld/schema/iasworld.asmt_all.yml
dbt/models/iasworld/schema/iasworld.land.yml
dbt/models/iasworld/schema/iasworld.oby.yml

This produces three tests, one for asmt_all, oby, and land, each of which tests that all values in pardat which are exempt, are exempt in the tested tables. 
It fails in two occasions, land (14 failures) and oby (3), while passing in asmt_all.

Define a dbt test to ensure that exempt pardat parcels are also exempt in all related tables

---

.github/workflows/pre-commit.yaml

This PR refactors the `.github/workflows/pre-commit.yaml` to use the `action.yaml` in the actions repo. However, there are key difference that makes it so that it isn't a 1:1 replacement. I'm not sure how to incorporate these differences, mostly because I am not familiar with the exact use case. I could build these into the `action.yaml`, or perhaps try to get some sort of conditional logic going.

Refactor pre-commit to use composite action

---

dbt/models/iasworld/schema/iasworld.pardat.yml
dbt/tests/generic/test_row_values_match_after_join.sql

This PR adds a iasWorld QC test for neighborhood codes that don't match their township, pursuant to the research in #275.
Closes #275.

Add test for nbhd code with mismatched township

---

dbt/models/iasworld/columns.md
dbt/models/iasworld/schema/iasworld.comdat.yml
dbt/models/iasworld/schema/iasworld.dweldat.yml
dbt/models/iasworld/schema/iasworld.oby.yml

In 2023, we began migrating from the `mktadj` column to the `external_occpct` column on `dweldat`, `comdat`, and `oby`. Prior to 2023, only `mktadj` should be populated in cases of fractional occupancy; in 2023, either `mktadj` or `external_occpct` (but not both) can be populated, representing the time when the fields were in transition; and starting in 2024, only `external_occpct` should be populated.
At the same time, we recently added `"5B"` as a valid option for `chgrsn` and `mktrsn` to help differentiate between 1-year reductions issued by our office and the board of review.
This PR adjusts our tests for the `mktadj`, `mktrsn`, and `chgrsn` columns on `dweldat`, `comdat`, and `oby` to reflect these two changes.
Closes #399.
Run the tests to ensure they execute properly:
```
dbt test …
```

Adjust `mktadj` tests to reflect the switch to `external_occpct`and new `5B` code

---

dbt/models/iasworld/schema/iasworld.dweldat.yml

This produces six tests where the following [table](https://github.com/ccao-data/wiki/blob/master/Data/Class-Definitions.pdf) identifies a date range.
The results of the tests are as follows:
iasworld_dweldat_yrblt_205_more_than_62_years_old - 36 failures
iasworld_dweldat_yrblt_206_more_than_62_years_old - 31 failures
iasworld_dweldat_yrblt_207_less_than_62_years_old - pass
iasworld_dweldat_yrblt_208_less_than_62_years_old - 1 failure
iasworld_dweldat_yrblt_278_less_than_62_years_old - 1 failure
iasworld_dweldat_yrblt_295_less_than_62_years_old - pass

Add a test to dweldat to make sure yrblt matches the class code

---

dbt/models/ccao/docs.md
dbt/models/ccao/schema.yml
dbt/seeds/ccao/ccao.pin_test.csv
dbt/seeds/ccao/docs.md
dbt/seeds/ccao/schema.yml

This PR moves the `pin_weird` table from S3 to dbt. It renames the table to better align with its use (of holding test cases), and instantiates it using dbt's seed functionality.
Related to #380.

Add `pin_test` dbt seed

---

aws-athena/views/default-vw_pin_universe.sql

Reporting on 2024 is pretty difficult with no 2024 spatial data. Let's try forward filling it in `vw_pin_universe` and see what that gets us.

Test conditionally forward filling `default.vw_pin_universe`

---

aws-athena/views/reporting-vw_assessment_roll_muni.sql
aws-athena/views/reporting-vw_pin_township_class.sql
dbt/models/reporting/docs.md
dbt/models/reporting/reporting.vw_assessment_roll_muni.sql
dbt/models/reporting/schema.yml

> In reporting, we currently have vw_assessment_roll and vw_top_5 for townships. I'd like to create two similar separate views for municipalities.
> ### Use case
> 
> - This is frequently requested data for Assessor Leadership; let's institutionalize it.
> 
> - I also want to have an auto-updating version of a [municipal dashboard](https://www.cookcountyassessor.com/node/1887075).
> 
> 
> ### Complication: Assessment cycles
> 
> the assessment system works on a township cycle, not a municipal cycle, so some municipalities might have some PINs in one assessment stage and other PINs in a different stage.
> ### Possible solution
> 
> I _think_ the best way around this is to add an additional column on the assessment_roll version indicating, for each municipality, for the year & stage, the …

Reporting views for municipalities

---

.github/workflows/build_daily_dbt_models.yaml

Our [daily dbt build](https://github.com/ccao-data/data-architecture/actions/runs/9017116315/job/24780765574) failed this morning with a role timeout. I'm fairly certain we just need to bump the role duration passed during the setup stage of the workflow.

Bump role duration for daily builds

---

aws-athena/views/default-vw_pin_appeal.sql

It looks like our logic in `vw_pin_appeal` for including ~2020 appeals is potentially wrong (or the underlying data has changed). This PR updates the logic to take the correct set of columns for 2020.
You can see from the table below that the change and reason code columns are entirely null for 2020. Each cell is the null proportion for that year and column.
<details>
<summary>See query</summary>
```sql
SELECT
year,
ROUND(SUM(CAST(change IS NULL AS int)) / CAST(COUNT(*) AS double), 3) AS change_np,
ROUND(SUM(CAST(reason_code1 IS NULL AS int)) / CAST(COUNT(*) AS double), 3) AS reason1_np,
ROUND(SUM(CAST(reason_code2 IS NULL AS int)) / CAST(COUNT(*) AS double), 3) AS reason2_np,
ROUND(SUM(CAST(reason_code3 IS NULL AS int)) / CAST(COUNT(*) AS double), 3) AS reason3_np, …
```

Update `vw_pin_appeal` with new post-2020 logic cutoff

---

dbt/models/default/schema/default.vw_pin_condo_char.yml
dbt/tests/generic/README.md
dbt/tests/generic/test_expression_is_false.sql

Our current `expression_is_true` dbt tests can lead to some weird backwards engineering trying to figure out how to invert logic given how it employs `NOT` before the `WHERE` clause it tests. Having an alternative to avoid these situations would be helpful.

Add `expression_is_false` dbt test macro

---

.github/workflows/build_daily_dbt_models.yaml

As discussed in https://github.com/ccao-data/aws-infrastructure/pull/26#discussion_r1609011282, there's currently an edge case in our dbt model dependency deployment pipeline that could bite us in the future. The problem is the combination of these three aspects of the pipeline:
* Model dependencies are only deployed as part of the `build-and-test-dbt` workflow, which runs on PRs being merged to the main branch
* Model dependencies are configured to expire every 90 days
* Model dependencies are required by the `build-daily-dbt-models` workflow, which is scheduled to run once a day
As such, it's possible for `build-daily-dbt-models` to run without model dependencies existing, if they happen to have expired before it runs.
This PR fixes this edge case by updating `build-daily-dbt-models` to …

Deploy dbt model dependencies before building daily models

---

dbt/requirements.txt

This housekeeping PR updates dbt-core to [1.8.1](https://github.com/dbt-labs/dbt-core/releases/tag/v1.8.1), released today.

Upgrade dbt-core to 1.8.1

---

.github/scripts/transform_dbt_test_results.py
dbt/package-lock.yml
dbt/packages.yml
dbt/tests/generic/test_sequential_values.sql

I noticed today that the categorization of tests performed by `transform_dbt_test_results.py` broke after we changed the name of our dbt project from `athena` to `ccao_data_athena` in https://github.com/ccao-data/data-architecture/pull/422, causing most of our tests to get incorrectly categorized as `miscellaneous`. This PR fixes that bug and removes the coupling of `transform_dbt_test_results.py` to the dbt project name so that we can change the name of the project without breaking the script in the future.
I also searched the repo to double-check that there aren't any more hidden references to the old project name hanging around, and as far as I can tell this is the last one.
Note that this PR also removes the dependency on `dbt_utils`, since I noticed that the last remaining use of a …

Fix broken categorization in `transform_dbt_test_results.py` and remove `dbt_utils` dependency

---

dbt/dbt_project.yml
dbt/profiles.yml

Reverts ccao-data/data-architecture#462. We're getting the following failure on Spark tables:
```
File "<stdin>", line 387, in <module>
File "<stdin>", line 239, in model
File "<stdin>", line 384, in <lambda>
File "<stdin>", line 292, in ref
File "<stdin>", line 378, in get_spark_df
File "/opt/amazon/spark/python/lib/pyspark.zip/pyspark/sql/session.py", line 700, in table
return DataFrame(self._jsparkSession.table(tableName), self._sc, self._jconf)
File "/opt/amazon/spark/python/lib/py4j-0.10.9.3-src.zip/py4j/java_gateway.py", line 1321, in __call__
return_value = get_return_value(
File "/opt/amazon/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 117, in deco
raise converted from None
pyspark.sql.utils.AnalysisException: Path does not exist: …
```

Revert "Configure high availability on all dbt tables"

---

.pre-commit-config.yaml
dbt/models/proximity/proximity.dist_pin_to_cta_route.sql
dbt/models/proximity/proximity.dist_pin_to_cta_stop.sql
dbt/models/proximity/proximity.dist_pin_to_metra_route.sql
dbt/models/proximity/proximity.dist_pin_to_metra_stop.sql
dbt/models/proximity/proximity.dist_pin_to_park.sql
dbt/models/proximity/proximity.dist_pin_to_university.sql
dbt/models/proximity/proximity.dist_pin_to_vacant_land.sql

This PR brings us up to date with the latest sqlfluff release, and ignores a few lines for a new rule ([ST03](https://docs.sqlfluff.com/en/stable/rules.html#rule-ST03)) that is incorrectly failing in cases where we define a CTE so that we can pass its name into a dbt macro.
Closes https://github.com/ccao-data/data-architecture/issues/456.

Upgrade sqlfluff to 3.0.7

---

dbt/requirements.txt

The `dbt clone` workflow we recommend in our README to our team members who are setting up dev environmens has been broken since https://github.com/ccao-data/data-architecture/pull/422 due to a bug in the way that the dbt-athena adapter handles cloning Python models (https://github.com/dbt-athena/dbt-athena/issues/645). That bug was fixed in https://github.com/dbt-athena/dbt-athena/pull/651 and has now been officially released in (v1.8.2)[https://github.com/dbt-athena/dbt-athena/releases/tag/v1.8.2], so this PR updates the dependency to fix the bug on our end as well.
I tested this by running `dbt clone --select reporting.ratio_stats --state master-cache` locally to confirm that it completed successfully.

Upgrade to dbt-athena v1.8.2 to fix cloning of Python models

---

.github/workflows/build_and_test_dbt.yaml
dbt/profiles.yml

I noticed during the process of investigating problems with https://github.com/ccao-data/data-architecture/issues/460 that our dbt targets all share the same workgroup for Athena PySpark. This isn't ideal from a permissions perspective, since it means that  dev and staging targets can access a role that has CRUD permissions over prod tables and views. This PR changes our profiles so that our dev and staging targets point to a dedicated staging Spark workgroup, `primary-spark-staging`, that only has CRUD permissions over dev/staging tables and views.
The PR also sneaks in one minor unrelated change: Recently as I've been debugging our builds more extensively, I've been finding myself wishing there was a way that we could manually dispatch a run that rebuilds the entire DAG. As far as I can …

Switch dev and staging dbt targets to dedicated staging Spark workgroup

---

.github/scripts/cleanup_dbt_resources.sh

The `cleanup-dbt-resources` workflow started raising errors after we merged #475 since it was still referencing the `print_s3_dependency_dir` macro that we deleted as part of that PR. See [here](https://github.com/ccao-data/data-architecture/actions/runs/9354399654/job/25747188925) for a sample broken workflow run (note that the 404 warning in the logs is irrelevant, since the script is configured to expect those kinds of 404s and continue execution after encountering them). Note that no resources remain in need of being cleaned up from these failed workflow runs, since they all failed on the very last step that has been functionally a no-op since https://github.com/ccao-data/data-architecture/pull/461.
See [this workflow run](https://github.com/ccao-data/data-architecture/actions/runs/935 …

Remove deleted `print_s3_dependency_dir` macro call from `cleanup-dbt-resources` workflow

---

dbt/dbt_project.yml
dbt/profiles.yml

Testing out more high availability tables following a successful experiment in https://github.com/ccao-data/data-architecture/pull/486.
We also bump the number of threads used by dbt for issuing queries to 10.

Configure high availability for `location` schema

---

dbt/dbt_project.yml
dbt/models/model/model.final_model.sql
dbt/profiles.yml

This PR reverts the changes in https://github.com/ccao-data/data-architecture/pull/476, effectively reimplementing https://github.com/ccao-data/data-architecture/pull/462 now that we've built confidence in the HA approach in https://github.com/ccao-data/data-architecture/pull/487 and https://github.com/ccao-data/data-architecture/pull/486.
We also bump our dbt thread count to 16 now that our Athena service quota has been increased to 50 concurrent DDL queries.

Switch the whole DAG back to high availability

---

dbt/dbt_project.yml
dbt/models/model/model.final_model.sql
dbt/profiles.yml

This PR reverts all the changes from #488, #487, and #486 that we made for testing dbt-athena high availability.

Revert all HA changes

---

docs/design-docs/reporting-sot.md

This PR adds a draft design document outlining the motivation, requirements, and design of reporting "source-of-truth" tables. We can use this PR to get everyone on the same page and possibly solicit feedback from other departments.
Closes #458.

Add initial SoT design doc

---

dbt/packages.yml

Quick PR to close #489. GitHub Actions isn't properly caching dbt packages because it expects the `packages.yml` file to exist as a key. Since we aren't currently using any packages, this file does not exist, and the hash function used for the key returns an empty string. Just replacing this with an empty file should fix the problem.

Add empty `packages.yml` as cache key

---

dbt/README.md

This PR persists some knowledge about debug logging to our docs.

Add debug logging docs to `dbt/README.md`

---

dbt/profiles.yml

The dbt [threads](https://docs.getdbt.com/docs/running-a-dbt-project/using-threads) argument specifies the maximum number of models that can be simultaneously built without breaking the dependency graph. We had it set to 5 for reasons I can't quite remember, but Athena can handle many more simultaneous queries (DDL statements, in this case). This PR bumps the maximum number of threads to 16. This should result in slightly faster full DAG builds.

Bump number of threads used by all dbt targets

---

.github/ISSUE_TEMPLATE/new-dbt-model.md
dbt/README.md
dbt/models/reporting/reporting.ratio_stats.py

This PR updates our dbt documentation in `dbt/README.md` and the `new-dbt-model` issue template to add guidance on creating Python models.
Closes #497.

Update dbt documentation to document Python models

---

.github/ISSUE_TEMPLATE/new-dbt-model.md

I noticed while showing off updates to the `new-dbt-model` issue template that the line breaks that we use in the Markdown file to make editing easier get reproduced in the final issue, where they are not automatically expanded out into full lines. This makes the final issue look a bit weird and hard to read. See [a draft issue](https://github.com/ccao-data/data-architecture/issues/new?template=new-dbt-model.md&title=Add+a+new+dbt+model) for an example (select the Preview tab to see how the issue gets rendered).
This PR expands out the lines in that issue template, which makes editing slightly more annoying but significantly improves the reading experience of the final issue. It also aligns the formatting of `new-dbt-model` with our other issue template, …

Expand lines in `new-dbt-model` issue template for friendlier formatting

---

dbt/models/default/schema/default.vw_pin_condo_char.yml

The test `default_vw_pin_condo_char_nonlivable_no_chars` occupies a bit of an awkward middle ground between a unit test and a data test. I've opened an issue to refactor it such that failures are more actionable (https://github.com/ccao-data/data-architecture/issues/515), but in the meantime, it's causing the full DAG build to fail ([example here](https://github.com/ccao-data/data-architecture/actions/runs/9507765142/job/26207844499)) so this PR bumps the threshold as a temporary workaround.
Evidence that this new threshold causes the test to warn instead of error in [this workflow run](https://github.com/ccao-data/data-architecture/actions/runs/9518288879/job/26238850535?pr=514#step:9:44).

Bump nonlivable chars test threshold

---

dbt/dbt_project.yml
dbt/profiles.yml

This PR is the latest in a long effort to get [high availability tables](https://github.com/dbt-athena/dbt-athena?tab=readme-ov-file#highly-available-table-ha) working with our dbt configuration (search ["high availability"](https://github.com/ccao-data/data-architecture/pulls?q=high+availability) in our PRs for the full history).
While deploying previous versions of this PR, we had seen strange behavior whereby dbt was deleting the underlying S3 immediately after creating them. We were able to debug this and determine that it happens only for pre-existing tables when switching from non-high-availability to high availability and from the `schema_table` naming scheme to `schema_table_unique`: In these cases, the Glue database retains a reference to an old version of the table with the …

Switch back to high availability tables

---

dbt/models/default/default.vw_pin_sale.sql
dbt/models/sale/sale.vw_ias_salesval_upload.sql
dbt/models/sale/schema.yml
dbt/models/shared_columns.md

This PR updates `vw_pin_sale` and `vw_ias_salesval_upload` with the new column structure from the [sales val migration](https://github.com/ccao-data/model-sales-val/pull/130/files). We also edit schema and shared_columns files accordingly.
Note: I will need to change the refs back to the prod table at some point after we do the migration.
I am getting a sql fluff error on the pre-commit check that I'm not entirely sure is working correctly, curious about your thoughts @jeancochrane. 
Eyeballing these queries confirm that things are not totally out-of-whack:
```sql
SELECT sv_is_outlier, COUNT(*)
FROM "z_ci_sales_val_migration_q2_2024_ias_design_doc_default"."vw_pin_sale"
WHERE sv_run_id is not null
GROUP BY sv_is_outlier
ORDER BY COUNT(*) DESC;
```
```sql
SELECT sv_outlier_reason1, …
```

Sales val migration q2 2024 ias world spec

---

dbt/requirements.txt

This PR updates `dbt-core` to [the latest release](https://github.com/dbt-labs/dbt-core/releases/tag/v1.8.3), which contains some minor security fixes to the docs JS dependencies.
I don't think anything in the changelog should affect us, but to be safe I ran a quick `build-and-test-model` run on `default.vw_card_res_char` and confirmed that things still generally work as expected ([see output here](https://github.com/ccao-data/data-architecture/actions/runs/9616775127/job/26527052111)).

Update dbt-core to 1.8.3

---

etl/etl.Rproj
etl/scripts-ccao-data-warehouse-us-east-1/spatial/spatial-parcel.R

This PR updates the parcel file ETL to add 6 new features for modeling. These features attempt to capture the complexity of the parcel shape, based on the idea that more "regular" shaped parcels are more desirable and are thus worth more, they were mostly taken from [this paper](https://eres.architexturez.net/system/files/P_20230206101430_7873.pdf). The 6 features are:
1. The standard deviation of the interior angles of the parcel polygon
2. The standard deviation of the parcel polygon edge length
3. The standard deviation of the parcel vertices' distance to the parcel centroid
4. The total number of vertices in the parcel polygon
5. The ratio of the length of the sides of the minimum spanning rotated rectangle
6. The ratio of the areas of the minimum spanning rotated rectangle and the …

Add new model features to capture parcel shape

---

etl/scripts-ccao-data-warehouse-us-east-1/spatial/spatial-parcel.R

[`st_make_valid()`](https://r-spatial.github.io/sf/reference/valid.html) actually uses two different methods, one for planar geometries and a different one for ellipsoidal geometries. The earlier st_make_valid call on the planar geometry (`geometry_3435`) actually still yields one or two parcels that are invalid in the ellipsoidal version, so this PR adds another st_make_valid call at the end of the script just to be safe.

Add extra `st_make_valid` call at end of parcel script

---

.github/workflows/test_dbt_models.yaml

I updated `transform_dbt_test_results.py` in https://github.com/ccao-data/data-architecture/pull/527 to clean up the CLI interface and add support for filtering results by township, but I neglected to update the usage in the `test_dbt_models` workflow, so now [it's failing](https://github.com/ccao-data/data-architecture/actions/runs/9906586814/job/27368438662). This PR tweaks the script call in `test_dbt_models` to get it passing again; see [here](https://github.com/ccao-data/data-architecture/actions/runs/9911093016/job/27383393115) for a successful run on this branch.

Update `test_dbt_models` workflow to reflect recent changes to `transform_dbt_test_results` script

---

.github/scripts/transform_dbt_test_results.py
.github/workflows/test_dbt_models.yaml

This PR updates the `.github/scripts/transform_dbt_test_results.py` script to output row-level test failure data to a parquet dataset with the name `test_run_failing_row`. This is intended to supplement the `test_run` dataset (which saves metadata about a specific run) and the `test_run_result` dataset (which saves aggregate statistics for tests at the township level).
In so doing, we also update `test_run_result` to include an nullable `column_name` attribute that matches the new `test_run_failing_row` dataset. This attribute has proven useful for the purposes of analysis, and saving it explicitly should be more robust than the current workflow where we extract the column name from the test name (which follows the pattern `iasworld_<tablename>_<column_name>_description` in cases where a …

Persist row-level test results in `transform_dbt_test_results` script

---

.github/scripts/deploy_dbt_model_dependencies.sh
dbt/models/reporting/reporting.ratio_stats.py
dbt/models/reporting/schema.yml

Fast follow on the changes from https://github.com/ccao-data/assesspy/pull/20. Need to bump the version number since I transferred the project to a `ccao-data` PyPI account and the old releases now no longer exist.

Bump assesspy to 1.2.0

---

dbt/models/ccao/docs.md
dbt/models/ccbor/docs.md
dbt/models/ccbor/schema.yml
etl/scripts-ccao-data-raw-us-east-1/ccbor/ccbor-appeals.R
etl/scripts-ccao-data-warehouse-us-east-1/ccbor/ccbor-appeals.R

ETL pipeline to take data from [BOR appeals open data asset](https://datacatalog.cookcountyil.gov/Property-Taxation/Board-of-Review-Appeal-Decision-History/7pny-nedm/about_data) and load it into athena. Data is more-or-less unaltered. Glue crawler for the `ccbor` database was also added.
See https://github.com/ccao-data/data-architecture/issues/548 for more details.
As of right now using the `RSocrata` package (since `jsonlite` can't handle the amount of data being gathered from the open data portal) which needs credentials. I've added them to `.Renviron`, but that's a file we track with git in this repo. So we'll need to figure out a solution for this.

Ingest BOR appeal data into lake

---

dbt/models/model/model.vw_card_res_input.sql
dbt/models/model/schema.yml

See https://github.com/ccao-data/data-architecture/issues/558
Long story short, `model.vw_card_res_input` is not currently unique by pin10, card, and year due to nearest neighbor joins. These joins introduce duplicates because some non-condo res parcels have 14-digit pins rather than the 10 we assume.

Investigate duplicates in `model.vw_card_res_input`

---

dbt/README.md
dbt/models/qc/schema.yml
dbt/scripts/export_models.py
dbt/selectors.yml

I learned from Will today that a few of the town close QC reports are specific to non-tri towns, meaning that he doesn't generate them for tri towns. This PR tweaks our tags, code, and docs for town close QC reporting to reflect this fact and allow us to export either tri town close QC reports or non-tri town close QC reports.
I tested this change by running the two versions of town close reports and confirming that the script exported the correct reports for each kind. To export a tri town:
```
python3 scripts/export_models.py --selector select_qc_report_town_close_tri --where "township_code = '72' and taxyr = '2024'"
```
To export a non-tri town:
```
python3 scripts/export_models.py --selector select_qc_report_town_close_non_tri --where "township_code = '20' and taxyr = '2024'"
```

Update QC report tags, code, and docs to split tri town close reports from non-tri towns

---

.pre-commit-config.yaml
dbt/models/reporting/reporting.ratio_stats.py
pyproject.toml

This PR updates our ruff config to enable sorting Python imports, which is disabled by default. We also update the linter pre-commit step to use the `--fix` flag, which enables autofixing for linter errors ([docs](https://docs.astral.sh/ruff/linter/#fixes)).
Note that I cancelled the `build-and-test-dbt` workflow, since this PR changes the `ratio_stats` script and I didn't want to bother rerunning it. Merging this PR should also rerun `ratio_stats` in prod; since we have high-availability enabled, this shouldn't cause a problem, but I'll plan to merge at a slow time and babysit the deployment just in case.
Closes https://github.com/ccao-data/data-architecture/issues/581.

Configure ruff to sort Python imports

---

socrata/socrata_upload.py

In https://github.com/ccao-data/data-architecture/pull/566 we added the script `socrata/socrata_upload.py`, which included some Python imports that were not properly sorted according to Python style guidelines. At the time the branch was created, ruff wasn't properly sorting our imports, a bug that we fixed in https://github.com/ccao-data/data-architecture/pull/582. The timing of these two PRs was mismatched such that `socrata_upload.py` snuck in without its imports being properly formatted, causing unrelated PRs to fail when linting that script ([see here for an example](https://github.com/ccao-data/data-architecture/actions/runs/10746131829/job/29806483280)).
This PR fixes the sort order in `socrata_upload.py`, which should prevent other PRs from being blocked by related linter errors. …

Fix Python import order in `socrata/socrata_upload.py`

---

dbt/models/ccao/docs.md
dbt/models/ccao/schema.yml
dbt/models/iasworld_test/schema.yml
dbt/seeds/ccao/docs.md
etl/scripts-ccao-data-warehouse-us-east-1/ccao/ccao-legacy.R

This PR adds:
- Scripts to parse and upload legacy mainframe fixed-width files to Athena
- dbt schema entries to expose the resulting legacy file tables in our dbt docs
- dbt schema entries for tables from the iasWorld test environment

Add scripts and schemas for iasWorld test and legacy files

---

dbt/models/iasworld/schema/iasworld.comdat.yml

Our nightly data tests are [currently failing](https://github.com/ccao-data/data-architecture/actions/runs/10825411156/job/30034328842#step:5:720) because https://github.com/ccao-data/data-architecture/pull/578 accidentally moved a test from `comdat.bldgval` onto `comdat.bld_modelid`. This PR fixes that mistake and unblocks our tests in the process.
Confirmation that this change causes the test to pass instead of erroring out:
```
$ dbt test --select iasworld_comdat_bldgval_between_0_and_1b
17:00:21  Running with dbt=1.8.3
17:00:22  Registered adapter: athena=1.8.2
17:00:26  Found 104 models, 9 seeds, 440 data tests, 164 sources, 10 exposures, 502 macros
17:00:26
17:00:29  Concurrency: 16 threads (target='dev')
17:00:29
17:00:29  1 of 1 START test iasworld_comdat_bldgval_between_0_and_1b …
```

Move `comdat.bldgval` test back onto the correct column

---

dbt/models/iasworld/schema/iasworld.pardat.yml
dbt/scripts/export_qc_town_close_reports.py

This PR makes two small fixes to data tests and QC reports that I caught while producing artifacts for Jefferson:
* Updates the `config.where` clause for `iasworld_pardat_nbhd_matches_spatial_town_nbhd` to filter for years using the standard `data_test_iasworld_year_start` and `data_test_iasworld_year_end` variables
* Tweaks the `is_tri()` function logic to return the correct output for tri towns in the `export_qc_town_close_reports` script
Evidence that these changes work:
```
$ dbt test --select iasworld_pardat_nbhd_matches_spatial_town_nbhd --store-failures
...
21:36:17  Completed with 1 error and 0 warnings:
21:36:17
21:36:17  Failure in test iasworld_pardat_nbhd_matches_spatial_town_nbhd (models/iasworld/schema/iasworld.pardat.yml)
21:36:17    Got 15 results, configured to fail if != …
```

Two small tweaks to data tests and QC reports

---

dbt/README.md
dbt/models/qc/qc.vw_report_town_close_res_edit.sql
dbt/models/qc/schema.yml
dbt/scripts/export_models.py
dbt/scripts/utils/export.py

I got a call from Valuations this morning to report that column sorting for the percentage columns in the `Res Edit` town close report wasn't behaving as they expected. It turns out that we're casting those values to strings, which causes Excel to sort them as strings instead of numbers.
This PR adds a new `number_format` option to the `export_format` config blocks that we use to format columns in the QC reports. It uses `number_format` to format the `Res Edit` percent columns as percentages, which causes sort behavior to work as expected.

Tweak Res Edit town close QC report to store percentage columns as numbers

---

dbt/models/sale/schema.yml
dbt/models/shared_columns.md

The original intent of this PR was to improve the docs; specifically explaining the `null` case for `sv_is_outlier`.
However we also had not updated the docs to reflect the changes made in [this PR](https://github.com/ccao-data/model-sales-val/pull/132) from [this issue](https://github.com/ccao-data/model-sales-val/issues/124).

Improve sales val dbt docs

---

dbt/scripts/utils/export.py

I noticed while setting up the `export_qc_town_close_reports` script on the VM that we have a typo in the `s3_staging_dir` config value. This is causing the creation of a duplicate S3 bucket that doesn't actually need to exist, and that the VM doesn't have permissions to access. This PR fixes this typo so that we can get rid of the duplicate bucket; once this is merged, I'll go ahead and delete the bucket.

Fix incorrect reference to athena results bucket in `export_models`

---

.github/workflows/socrata_upload.yaml
dbt/models/default/exposures.yml
socrata/requirements.txt
socrata/socrata_upload.py

This github workflow is currently failing, this PR is an attempt to fix it.
- Remove limits from sql queries
- Change parcel universe asset id to actual open data portal asset id

Fix socrata upload actionworkflow

---

dbt/models/ccao/docs.md
dbt/models/ccao/schema.yml
etl/scripts-ccao-data-warehouse-us-east-1/ccao/ccao-legacy.R

This PR follows up on Dan's work in https://github.com/ccao-data/data-architecture/pull/589 to add legacy data extracts from MV to the data lake in order to enable our work to compare homeowner exemptions between data sources.

Add homeowner exemption legacy extract to data lake

---

dbt/macros/aggregate_cdu.sql
dbt/models/default/default.vw_pin_status.sql
dbt/models/default/schema/default.vw_pin_status.yml
dbt/seeds/ccao/ccao.cdu.csv
dbt/seeds/ccao/docs.md
dbt/seeds/ccao/schema.yml

This PR:
- Changes the `dweldat` column feeding `dweldat_cdu_code` in `default.vw_pin_status` to `user16`
- Adds a CDU codes dbt seed with up-to-date CDU codes
- Joins code descriptions onto `default.vw_pin_status`

Create CDU codes dbt seed and add CDU descriptions to `default.vw_pin_status`

---

dbt/models/default/columns.md
dbt/models/default/default.vw_pin_permit.sql
dbt/models/default/docs.md
dbt/models/default/schema/default.vw_pin_permit.yml

This PR updates our dbt docs for the `default.vw_pin_permit` view based on our conversation with subject matter experts. It also makes one small tweak to the view code itself to fall back to the `iasworld.permit.wen` field when creating the `default.vw_pin_permit.date_updated` field in cases where the underlying `iasworld.permit.udate3` field is null.

Flesh out permit docs based on feedback

---

dbt/models/iasworld/schema/iasworld.comdat.yml
dbt/models/iasworld/schema/iasworld.dweldat.yml
dbt/models/iasworld/schema/iasworld.oby.yml
dbt/models/shared_columns.md

`user16` and `cdu` columns can be a little confusing in `oby`, `dweldat`,and `comdat`. This PR clarifies what each column contains.

Update `cdu` and `user16` documentation

---

etl/scripts-ccao-data-warehouse-us-east-1/ccao/ccao-legacy.R

As part of the ongoing exemption comparison work, I had to manually clean the file that represented an export of the `OWNR ` table from the AS/400 to strip out some ASCII null characters that were being used instead of spaces (and thereby causing `reader::read_fwf()` to read the wrong column positions for those rows). This PR adds a single comment to the `ccao-legacy.R` script that processes that export to note for posterity that the export has been manually edited.

Add comment about manual cleaning to `ccao-legacy.R` script

---

dbt/models/reporting/docs.md
dbt/models/reporting/reporting.vw_pin_school_impact.sql
dbt/models/reporting/schema.yml

See https://github.com/ccao-data/data-architecture/issues/627

Properties that most impact each school district's property taxes

---

dbt/models/default/default.vw_pin_permit.sql

This PR fixes a small mismatch in the `default.vw_pin_permit` view, wherein two fields (`permit_type` and `job_code`) were present in the view but had no docs while two other fields (`job_code_secondary` and `job_code_primary`) had docs but were not present in the view.
The key problem here is a renaming of field mappings that I neglected to complete in the docs:
| iasWorld fieldname | iasWorld display name | First draft view fieldname | Final draft view fieldname |
| ------------------- | ---------------------- | -------------------------- | -------------------------- |
| `WHY`                    | Pri Job Desc                | `job_code_primary`           | `permit_type`                    |
| `USER42`               | Sec Job Desc              | `job_code_secondary`      | `job_code` …

Rename permit job code fields to better align with iasWorld

---

.pre-commit-config.yaml
dbt/scripts/check_sort_dbt_yaml_files.py

https://github.com/ccao-data/data-architecture/pull/644 got merged in before we could implement two pieces of feedback:
* Adjusting the `exclude` attribute of the pre-commit hook to be more precise and only exclude files in a directory matching the string `venv/` rather than any file containing the substring `venv`, which could exist without being in a venv dir ([comment](https://github.com/ccao-data/data-architecture/pull/644#discussion_r1847173185))
* Adding a docstring to explain the different cases in which the linter runs, and how it expects arguments ([comments](https://github.com/ccao-data/data-architecture/pull/644#discussion_r1847175457))
In the course of implementing these two pieces of feedback, I also noticed that the logic to check for properly sorted tests is only looking at …

Further improvements to dbt sort order linter

---

dbt/selectors.yml

This PR fixes a bug in our `select_data_test_iasworld` selector that I introduced in https://github.com/ccao-data/data-architecture/pull/638. The `resource_type:test` filter should be joined to the `tag:data_test_iasworld` filter using an [intersection](https://docs.getdbt.com/reference/node-selection/set-operators#intersections) rather than a [union](https://docs.getdbt.com/reference/node-selection/set-operators#unions). If we use a union instead, the selector will return _all_ data tests instead of only data tests tagged with `data_test_iasworld`. I noticed this while debugging a [failing workflow](https://github.com/ccao-data/data-architecture/actions/runs/11919381878/job/33218963393) that was running the wrong number of tests. I mixed this up because `union` has a special meaning the …

Fix `select_data_test_iasworld` selector by using set intersection

---

dbt/models/default/default.vw_pin_universe.sql

This column was only needed in order to populate the open data asset Parcel Universe with a row id column, which is done. Moving forward row id will be generated on the fly by the github action used to update the open data asset.

Remove rowid from `default.vw_pin_universe`

---

dbt/models/reporting/docs.md
dbt/models/reporting/reporting.res_report_summary.sql
dbt/models/reporting/reporting.res_report_summary_sales_input.sql
dbt/models/reporting/reporting.res_report_summary_values_input.sql
dbt/models/reporting/schema.yml

This PR fixes our broken `build-daily-dbt-models` workflow by improving build performance for the `reporting.res_report_summary` table, which has been exhausting Athena query resources ever since we merged https://github.com/ccao-data/data-architecture/pull/641.
The approach in this PR is to take the CTEs that the query reuses for aggregation and split them out into input tables that we materialize on the same schedule as `reporting.res_report_summary`. Tables improve performance over CTEs in this case because [Athena treats CTEs the same as subqueries and views](https://docs.aws.amazon.com/athena/latest/ug/select.html#select-parameters), that is to say, it will rerun the underlying query code every time the CTE is referenced.
Closes …

Fix `reporting.res_report_summary` builds by turning input CTEs to tables

---

dbt/models/iasworld/columns.md

This PR updates our docs for the `chgrsn`/`mktrsn` fields to reflect the new 5C value, which indicates a one-year Board reduction that is _not_ implemented via occupancy.
Note that I also double-checked our tests and QC reports to confirm that nothing else needs to change based on this new code.

Update docs to reflect new card code 5C

---

dbt/models/default/exposures.yml
socrata/socrata_upload.py

Well, this PR seems to address the issues that were blocking deployment of out Socrata SODA API github action from working on `default.vw_pin_sale` and its Open Data asset "Parcel Sales", but the outcome doesn't bode well for deploying the API script as an alternative for the socrata agent running on the server.
I can run the github action now [without any errors](https://github.com/ccao-data/data-architecture/actions/runs/12127852104/job/33813006378) _on small samples of data_. Anything large, we get our [connection reset](https://github.com/ccao-data/data-architecture/actions/runs/12127715772/job/33812565042) by Socrata's server. Perhaps I'm misunderstanding what's happening in those logs, but if I'm not, I'll have to reach out to them and see if there's any solution for this issue. In …

Fix socrata api github action primary key handling

---

dbt/models/location/docs.md
dbt/models/location/location.census_2020.sql
dbt/models/location/schema.yml
dbt/models/model/model.vw_pin_shared_input.sql

Right now `model.vw_pin_shared_input` is not being properly filled by `other.ihs_index`. This is because IHS has switched from using 2010 PUMA geoids to 2020 puma geoids, and we were using 2010 geoids to join these two tables together. This PR replaces `location.census_2010` with `location.census_2020` in order to make this join can function as it did previously.
```
library(DBI)
library(dplyr)
library(noctua)
library(mapview)
library(sf)
noctua_options(cache_size = 10, unload = TRUE)
AWS_ATHENA_CONN_NOCTUA <- dbConnect(
noctua::athena(),
rstudio_conn_tab = FALSE
)
dbGetQuery(
conn = AWS_ATHENA_CONN_NOCTUA,
"SELECT
meta_pin,
loc_longitude,
loc_latitude,
loc_census_acs5_puma_geoid
FROM z_ci_665_investigate_join_that_is_dropping_ihs_index_data_model.vw_pin_shared_input
where …
```

Update PUMA geoids for IHS data join

---

dbt/models/default/schema/default.vw_card_res_char.yml

This PR fixes our [failing data integrity tests](https://github.com/ccao-data/data-architecture/actions/runs/12189451367/job/34004613229#step:7:275) by slightly reducing the threshold for the `row_count` test on `default.vw_card_res_char`.
The `default_vw_card_res_char_row_count` test first failed during the scheduled weekly data integrity tests on [11/25/24](https://github.com/ccao-data/data-architecture/actions/runs/12008766106/job/33472098003#step:7:265). The most recent confirmed pass prior to this date was during the scheduled run on [11/18/24](https://github.com/ccao-data/data-architecture/actions/runs/11891194724/job/33131443902#step:7:80). Here are the steps I took to build confidence that the test started failing due to changes in the underlying iasWorld data, and not in our …

Reduce threshold for row count test on `default.vw_card_res_char`

---

.github/workflows/test_dbt_models.yaml
.github/workflows/test_iasworld_data.yaml

There is currently a bug in our weekly scheduled data integrity tests: Failing tests do not cause the workflow to fail, so we never get notified of them. ([See here for an example workflow run that should have failed](https://github.com/ccao-data/data-architecture/actions/runs/12118092672/job/33781887419#step:7:265).) This makes sense in that the `test-dbt-models` workflow was originally intended to be used exclusively to run iasWorld tests, so it doesn't fail the workflow if tests fail, because we expect some iasWorld tests to fail. This doesn't work for data integrity tests, however, since in the case the workflow _should_ fail if any test fails.
I thought about modifying the `test-dbt-models` workflow and its underlying `run_iasworld_data_tests.py` script to add a new flag to exit with …

Split out `test-iasworld-data` workflow from `test-dbt-models` so that data integrity tests will fail properly

---

etl/renv.lock
etl/scripts-ccao-data-warehouse-us-east-1/ccao/ccao-commercial_valuation.R

While adding commercial data documentation to the wiki I was trying to determine if there is a way to define primary keys for the data (I couldn't). I did, however, determine that there were some pretty bad values for `keypin` in the data. We try to clean this data as little as possible, but given the importance of `keypin`, it feels prudent to make sure we don't have rows with random notes or "TOTAL PINS" as `keypin`.
This PR reduces the size of the dataset by about 500 rows and cleans they `keypin` column in about 1000 more.

Fix keypin column in commercial valuation data

---

dbt/models/default/default.vw_pin_appeal.sql
dbt/models/default/docs.md
dbt/models/default/exposures.yml
dbt/models/default/schema/default.vw_pin_appeal.yml
dbt/models/iasworld/columns.md
dbt/models/iasworld/schema/iasworld.htpar.yml

`default.vw_pin_appeal` is not unique by `pin`, `year`, `case_no` as our docs suggest it should be. There are actual duplicates in `iasworld.htpar` that need to be removed. While I was trying to sort this out, Mirella told me we should also be much more parsimonious in terms of which values for `htpar.heartyp` we include in order to exclude things like PTAB adjustments and erroneous exemptions.
> Yes, the only hearing types you should be pulling if you are strictly focusing on appeal data are the ones listed below:
> 
> ![image](https://github.com/user-attachments/assets/5e39d8f8-b5e6-481e-afb3-78f867f71706)
> 
> O = Omitted Assessments, which are new for 2024 and by next year, there will the following new ones as well as others that will be used by the Tax side:
> 
> E = COE only
> 
> EE …

Make `vw_pin_appeal` unique by `pin`, `year`, `case_no`

---

dbt/models/default/schema/default.vw_pin_sale.yml
dbt/models/default/schema/default.vw_pin_sale_combined.yml

Currently, the error threshold for `vw_pin_sale_combined` is so close to the total count of failing records that if any new records with dupes get added (even if the dupes are expected) [it will cause the whole test to fail](https://github.com/ccao-data/data-architecture/actions/runs/12234395035/job/34123504238#step:7:274). On the other hand, the threshold for `vw_pin_sale` is much higher than the actual count, such that we might accidentally miss a problem if it's subtle enough. Both of these cases are problems since we only want the test to fail if we've changed something with the view that causes us to create artificial dupes. This PR bumps the number of allowed dupes for both tests and lines their thresholds up more consistently with the current number of failures, with the goal of …

Tweak thresholds and number of allowed dupes for duplicate tests against sale views

---

.github/workflows/deploy_dbt_docs.yaml

Now that our GitHub runners are on Ubuntu 24.04, the Mermaid diagram generation in our dbt docs deployment pipeline [is breaking](https://github.com/ccao-data/data-architecture/actions/runs/12362955038/job/34503342849#step:6:28) due to [an obscure AppArmor rule change](https://github.com/mermaid-js/mermaid-cli/issues/730#issuecomment-2408615110) that affects Puppeteer sandboxes. This PR implements the recommended solution from that issue by using [`aa-exec`](https://manpages.ubuntu.com/manpages/noble/man1/aa-exec.1.html) to confine the Mermaid process to a dedicated profile.
Full disclosure: I don't totally understand what's going on with this AppArmor rule change, but I think the stakes are pretty low, since we're only using Puppeteer via …

Fix dbt docs deployment for new Ubuntu 24.04 runners

---

dbt/models/default/default.vw_pin_universe_temp.sql

This is a stopgap measure to make updating the open data 'Parcel Universe' manageable. Presently it is so large that doing things like adding columns leads to the asset getting orphaned while attempting to load the data into memory, which is a prerequisite for publishing updates to the data. It might not ultimately work, but it's worth a try. Not a longterm solution as we plan to move to a one-year only version of Parcel Universe.
Shouldn't affect what the public sees on the open data portal.

Create baby version of `default.vw_pin_universe`

---

dbt/models/default/schema/default.vw_card_res_char.yml

The row count test for `default.vw_card_res_char` failed during [the most recent weekly data integrity test run](https://github.com/ccao-data/data-architecture/actions/runs/12465835312/job/34792318112#step:7:276). We saw a similar failure [two weeks ago](https://github.com/ccao-data/data-architecture/pull/672), which we believed to be caused by changes in the underlying iasWorld data. I followed a similar set of steps to investigate this week's failure, including checking out the [last commit that succeeded](https://github.com/ccao-data/data-architecture/actions/runs/12362767451) and rebuilding [the full set of view dependencies](https://ccao-data.github.io/data-architecture/#!/overview?g_v=1&g_i=%2Bdefault.vw_card_res_char) at that point in time to confirm that the test still fails. …

Set threshold dynamically for `default.vw_card_res_char` row count test based on iasWorld data

---

dbt/models/qc/qc.vw_ic_reference_all_towns_com_bldg_detail.sql

IC identified a small bug in one of the reference queries we started exporting for them in https://github.com/ccao-data/data-architecture/pull/678: We're joining the `ccao.commercial_minor_subclass` table to the _major_ subclass code rather than the minor code, which is producing the wrong human-readable descriptions for minor subclasses. This PR is a one-line change that fixes that bug.
I tested this change by rerunning the table and confirming the output for the `minor_subclass` column displays the correct human-readable description.

Fix `minor_subclass` join in `qc.vw_ic_reference_all_towns_com_bldg_detail`

---

socrata/socrata_upload.py

This PR makes sure all column names are retrieved from an open data asset and that if any chunk sent to socrata is larger than 10,000 rows it gets sub-chunked into chunks with less than 10k rows.
It also uses a [session object from the requests library](https://requests.readthedocs.io/en/latest/user/advanced/) in order to pool connections. We were getting 500 errors in the past, possibly because too many requests were being sent, and switching to connection pooling resolved that.

Test urllib fix

---

etl/scripts-ccao-data-warehouse-us-east-1/sale/sale-mydec.R

We have ~150 `-Inf` values for the senior homestead exemption that are introduced by taking the max exemption values within sales in the mydec data when there are only `NULL`s:
This didn't use to be an issue, but apparently the mydec data has some rows with NULL for exemption values now.
This PR makes sure any `-Inf` values are re-coded back to NULL for all exemption columns.

Remove `-Inf` from `sales.mydec`

---

dbt/models/default/default.vw_pin_sale.sql
dbt/models/default/schema/default.vw_pin_sale.yml

This PR adds line_9 ptax form columns to `default.vw_pin_sale`. We also add some docs for the columns in the schema directory.
Not sure if all columns should be added or just a subset. Currently I've added them all. Let me know @ccao-jardine @Damonamajor

Add line 9 ptax info to `default.vw_pin_sale`

---

socrata/socrata_upload.py

The default workflow value for years, 'all', was not being handled correctly since it becomes a list during ingest. Additionally, spaces in the years input could lead to year values not being handled correctly.
Since the columns that get updated currently depend on how the response from the API and the column names of the athena view that feeds the asset match up, it'd be nice to be able to confirm that all expected columns are in fact going to be updated.

Ensure socrata workflow inputs are handled correctly

---

dbt/models/model/columns.md

One small blocker for https://github.com/ccao-data/model-res-avm/pull/315: When we pull descriptions for the `Features Used` table in the model README, we grab the first sentence of the description (if a feature description contains multiple sentences). Two features, `shp_parcel_mrr_area_ratio` and `shp_parcel_mrr_side_ratio`, include Markdown-formatted links in the first sentence of their feature descriptions, but our `Features Used` table output can't parse Markdown. This PR moves those links to the last sentence of the feature descriptions so that the descriptions are compatible with the `Features Used` table for the model.

Clean up descriptions for parcel shape features so they are readable in model feature table

---

dbt/models/open_data/open_data.vw_parcel_sale.sql

Quick fix to https://github.com/ccao-data/data-architecture/pull/691 that makes sure the only row id that isn't a product of a `concat` operation is a string.

Ensure sales view row id is string

---

dbt/models/default/default.vw_pin_permit.sql

There are currently values of "null" in the permit view. Ideally this column should be able to be coerced into an integer without losing any data.
```
with results AS (
select distinct recheck_year,
'old' as old
from default.vw_pin_permit
union all
select distinct CAST(recheck_year AS varchar),
'new'
from z_ci_remove_null_from_recheck_year_column_default.vw_pin_permit
)
select *
from results
order by old,
recheck_year desc
```
recheck_year | old
-- | --
2505 | new
2025 | new
2024 | new
2023 | new
2022 | new
2021 | new
  | new
null | old
2505 | old
2025 | old
2024 | old
2023 | old
2022 | old
2021 | old
  | old
  | old

Ensure `recheck_year` has no non-numeric values

---

dbt/models/default/docs.md

I have had to look up why there are parcels missing a value for "x district" in parcel universe too many times.

Add nuance for `default.vw_pin_universe`

---

dbt/models/open_data/exposures.yml

https://github.com/ccao-data/data-architecture/pull/718 fixed one problem with our open data asset tests, but tests [are still failing](https://github.com/ccao-data/data-architecture/actions/runs/13139044701/job/36661398317#step:5:37) because we're trying to test new assets that are not yet public so our script gets a 403 when querying them. This PR disables tests for those assets to resolve the failures. We can re-enable these tests once the assets are public.
The workflow is still failing due to new parcel shapes, but you can confirm that it's not erroring out anymore: https://github.com/ccao-data/data-architecture/actions/runs/13139890483/job/36664237973

Disable open data asset tests for private assets until they are public

---

dbt/models/model/model.vw_pin_shared_input.sql

This fixes an issue discovered in [336](https://github.com/ccao-data/model-res-avm/issues/336), where school districts were NA in elementary or secondary and had a valid unified school district. This simply coalesces the values during the shared input step.

Modify School districts to fill with unified if NA

---

dbt/models/proximity/proximity.cnt_pin_num_foreclosure.sql

This fixes an issue discovered in [336](https://github.com/ccao-data/model-res-avm/issues/336), where PINs with 0 foreclosures within 1/2 a mile returned values of NA. This coalesces the result to 0 if there are 0 pins in that radius.

Fix foreclosure script to work with values of 0

---

dbt/models/location/location.crosswalk_year_fill.sql
dbt/models/location/location.tax.sql
dbt/models/location/location.vw_pin10_location_fill.sql
dbt/models/location/schema.yml

During model QC, we realized that a number of location features have unusual patterns of missingness over time (https://github.com/ccao-data/model-res-avm/issues/336).
I tested this PR with two new unit tests, one for `location.vw_pin10_location_fill` and one for `location.crosswalk_year_fill`, along with thorough QC of the two tables. In particular, I checked two things:
* The `year`, `{feature_name}_fill_year`, and `{feature_name}_data_year` columns in `location.crosswalk_year_fill` make sense for each feature
* The counts of missing values for each feature in `location.vw_pin10_location_fill` look reasonable when grouped by year
* By "reasonable", I mean to say that the number of missing records corresponds to the number of parcels that do not have a shape for the fill year
Note that …

Fix missing years of filled location data

---

dbt/models/reporting/schema.yml

Quick PR to suppress PRB test failures in `reporting.ratio_stats` for the pre-mailed stage. We've been getting a test failure for Cicero this year and after inspection the sales data looks fine - there's nothing to be corrected. Pre-mailed is a bit of an odd stage so for now we'll loosen the PRB test threshold for that stage to avoid constant failure alerts while maintaining the stricter alerts for other stages.
[Here's our quick and dirty sales investigation.](https://github.com/user-attachments/files/18734929/prb.zip)

Loosen PRB test threshold for `pre-mailed` assessment stage

---

dbt/models/model/schema.yml

In https://github.com/ccao-data/data-architecture/pull/669 we changed `model.vw_pin_shared_input` to materialize as a table, but we neglected to tag it with the `daily` tag so that it would get rebuilt every day by the [`build-daily-dbt-models` workflow](https://github.com/ccao-data/data-architecture/actions/workflows/build_daily_dbt_models.yaml). This PR adds that missing tag.
Proof that the tag works:
```
(dbt) ~/data-architecture/dbt$ dbt list --select tag:daily
22:43:32  Running with dbt=1.9.1
22:43:33  Registered adapter: athena=1.8.4
ccao_data_athena.model.model.vw_card_res_input
ccao_data_athena.model.model.vw_pin_condo_input
ccao_data_athena.model.model.vw_pin_shared_input
...
```

Tag `model.vw_pin_shared_input` for daily materialization

---

dbt/models/default/default.vw_pin_condo_char.sql

Since we don't have any 'PS' CDUs yet, this code shouldn't result in any changes to our data, and doesn't:
```
select
count(*)
from iasworld.oby
where user16 = 'PS'
```
yields 0, as does
```
select
count(*)
from iasworld.comdat
where user16 = 'PS'
```
```
select
is_parking_space,
parking_space_flag_reason,
is_question_garage_unit,
is_common_area,
'old' as source
from default.vw_pin_condo_char
union all
select
is_parking_space,
parking_space_flag_reason,
is_question_garage_unit,
is_common_area,
'new' as source
from z_ci_add_new_parking_space_code_to_nonlivable_construction_default.vw_pin_condo_char
```
|skim_variable          |source|n_missing|logical.mean|logical.count             |
|-----------------------|------|---------|------------|--------------------------|
|is_parking_space …

Add new parking space CDU code to nonlivable construction

---

dbt/models/default/default.vw_pin_status.sql
dbt/models/default/schema/default.vw_pin_status.yml

This PR adds a new column `has_recent_assessable_permit` to the `default.vw_pin_status` view. This column looks for assessable permits issued between January 1st of the year two years prior to the parcel year and December 31st of the parcel year, returning `TRUE` if any such permits exist and `FALSE` otherwise.
This PR doesn't yet add the new column to the `open_data.vw_parcel_status` view. Do we want to do that now, or wait till later @wrridgeway?
Connects https://github.com/ccao-data/model-res-avm/issues/340.

Add assessable permits flag to `vw_pin_status` view

---

.github/workflows/socrata_upload.yaml
dbt/models/open_data/exposures.yml
socrata/socrata_upload.py

This PR removes chunking by township as an option for socrata uploads. Now that the script automatically chunks any group larger than 10,000 rows being able to dictate which years we'd like to upload is more than enough user choice.
I'm going to have to add functionality for handling multiple assets in one go in order to automate socrata uploads in a future PR, and simplifying this script as much as possible in preparation for that will save some time and energy.
I tested all the possible configurations of overwriting and year values, and all of the jobs ran as expected:
https://github.com/ccao-data/data-architecture/actions/runs/13421072113/job/37493591749
https://github.com/ccao-data/data-architecture/actions/runs/13421200605/job/37494008961 …

Remove township as a choice for socrata chunking

---

dbt/models/open_data/open_data.vw_sf_mf_improvement_char.sql

While investigating every open data asset for parity with the open data db, I came upon two columns that need to be but are not currently being transformed. These were the only two I could find.
```
select char_attic_fnsh, char_gar1_area, count(*) as count
from z_ci_align_open_data_db_columns_with_socrata_open_data.vw_sf_mf_improvement_char
group by char_attic_fnsh, char_gar1_area
```
char_attic_fnsh | char_gar1_area | count
-- | -- | --
Living Area | No | 3134847
  | No | 3472
Living Area | Yes | 179158
Partial | Yes | 1387
Partial | No | 181195
Partial |   | 99
  | Yes | 1609
Living Area | | 954
None |   | 4910
None | Yes | 2048661
  |   | 64803
None | No | 23931299

Align open data db transformations with socrata

---

dbt/models/default/default.vw_pin_address.sql
dbt/models/default/default.vw_pin_exempt.sql
dbt/models/default/default.vw_pin_universe.sql
dbt/models/default/default.vw_pin_value.sql
dbt/models/default/schema/default.vw_pin_address.yml
dbt/models/default/schema/default.vw_pin_exempt.yml
dbt/models/default/schema/default.vw_pin_universe.yml
dbt/models/default/schema/default.vw_pin_value.yml
dbt/models/model/model.vw_pin_shared_input.sql
dbt/models/reporting/reporting.vw_pin_most_recent_sale.sql
dbt/models/reporting/reporting.vw_pin_township_class.sql
dbt/models/reporting/schema.yml

Class `999` are test parcels and don't serve any purpose being in our athena databases. We can leave them in `default.vw_pin_status` since that view explicitly tracks them. I only applied these changes to views that use `pardat` or `asmt_all` as a base and join other sources onto those tables. Views that join `pardat` or `asmt_all` onto other sources as a base shouldn't have any class `999` parcels to worry about; they only seem to exist in `pardat` and `asmt_all` and I checked every view in the `default` db that wasn't built on one them to confirm this (included appeals, sales, etc.). The reporting view that was updated doesn't have any differences in row count because we're already inner joining on `ccao.class_dict` which doesn't contain class `999`.
```
select 'pardat' as "table", …
```

Remove class 999 from universe

---

dbt/models/qc/qc.vw_ic_reference_all_non_res_pin_level_prior_year_vals.sql

This PR fixes a small bug that Valuations noticed in the QC view that IC uses for comparing prior year values. The view should return prior year AVs and MVs for all parcels in the current year, but it's returning current year AVs instead. The source of the bug is that the query currently joins `pardat` to `aprval` on `aprval.taxyr + 1 = pardat.taxyr` in order to get prior year MVs for parcels in the current year, but then it joins `asmt_all` to `pardat` using `taxyr`, which returns current year AVs. By joining `asmt_all` to `aprval` using `taxyr` instead, we return prior year AVs to match the prior year MVs.
Valuations has confirmed that this fix works on their end.

Pull prior year AVs to match prior year MVs in prior year val IC QC view

---

dbt/models/default/default.vw_pin_permit.sql
dbt/models/default/schema/default.vw_pin_permit.yml
dbt/models/open_data/open_data.vw_permit.sql

This new column allows the the socrata api script to treat the permit view the same as every other view. There are unfortunately three null values in the `year` column, which we can usually assume is complete. This feels like something we should ask the permit team to address rather than scripting out a workaround.

Add year column to permit views

---

.github/workflows/socrata_upload.yaml
dbt/models/open_data/exposures.yml
socrata/socrata_upload.py

This started as trying to allow this script to accept multiple assets, but working with it was a chore and it was clear it could be simplified and improved.
This PR really just shifts a lot of the looping and year handling to the query building and upload functions and removes a lot of `overwrite` parameter handling involving a `count` variable by only allowing `overwrite` to be true the first time it's handled.

Simplify Socrata API script and allow multiple assets to be updated

---

dbt/models/qc/schema.yml
dbt/scripts/utils/export.py

The COMDAT details view that we export daily for IC contains a data type mismatch that is currently causing the workbook to fail to export: A column is configured as an integer, but contains float values. This PR changes that column config to a float instead of an int.
We also make an unrelated quality-of-life tweak to the portion of the code that parses data types in order to make it more maintainable in the long run.

Fix export problem in IC reference file for COMDAT details

---

.github/workflows/socrata_upload.yaml
socrata/socrata_upload.py

This PR should address [two issues](https://github.com/ccao-data/data-architecture/actions/runs/13817905136) that surfaced during our first test of running the socrata api script on a scheduled workflow:
- After one hour the runner's AWS token expired and it could no longer query Athena. This was because I added an unnecessary `Configure AWS credentials` step to the workflow what reduced how long the aws token is valid from 4 to 1 hours.
- The workflow logs are not necessarily printed in order which makes debugging difficult
---
Putting this here since it's [poorly documented](https://github.com/laughingman7743/PyAthena/blob/2787190871d6be6f18f7ff1fa61c8e570cd2d7e4/pyathena/util.py#L41) and was hard to find despite us not needing it for this PR:
```
from pyathena.util import RetryConfig …
```

Remove unecessary aws credentials step and fix buffered workflow logs

---

dbt/models/ccao/docs.md
dbt/models/default/docs.md
dbt/models/default/schema/default.vw_pin_sale.yml

I did a quick review of our docs while fleshing out https://github.com/ccao-data/data-architecture/issues/770 and discovered a couple spots where our docs are not exactly correct about row uniqueness. This PR fixes those spots and also tweaks a couple of tests for `default.vw_pin_sale` to better reflect the two different uniqueness conditions.

Tweak some dbt docs for uniqueness based on a review of our models

---

dbt/models/open_data/exposures.yml
dbt/models/open_data/open_data.vw_permit.sql

This column is difficult to understand and rather dirty, it seems more confusing than helpful to include on the open data portal. Part of https://github.com/ccao-data/data-architecture/issues/776.
@ccao-jardine Jean and I feel it's best to just remove this column rather than try to explain it to the public since we're not entirely sure ourselves how it works, even after reaching out to field.

Remove `assessment_year` column from `open_data.vw_permit`

---

.github/scripts/deploy_dbt_model_dependencies.sh
dbt/models/reporting/schema.yml

We upgraded the version of `assesspy` that we use when building `reporting.ratio_stats` in https://github.com/ccao-data/data-architecture/pull/740, but we neglected to update the dependency configuration in `models/reporting/schema.yml` that the `build-daily-dbt-models` workflow uses to determine which versions of Python dependencies to deploy. This is causing `build-daily-dbt-models` [to fail consistently](https://github.com/ccao-data/data-architecture/actions/runs/14195532197/job/39769687992). This PR fixes the failing workflow by updating the dependency configuration to point to the correct version of `assesspy`.
See [here](https://github.com/ccao-data/data-architecture/actions/runs/14200537049/job/39786149060?pr=779#step:7:1) for evidence that the new version of `assesspy` deploys …

Fix dependency version for `assesspy` in `ratio_stats`

---

dbt/models/open_data/exposures.yml
socrata/socrata_upload.py

This won't fix randomly getting denied by Socrata's API, but it will make what we upload smaller so we're less likely to run up against tokens expiring, runners timing out, etc.
- Only upload most recent year for each asset. Permits asset has a row from 2032, so if most recent year is > whatever the current year is, script will default to current year. Previously we were uploading current year and/or current year - 1 for every asset, depending on which years are available in the asset.
- Added dbt tag for parcel status asset so it won't get updated since it's private.
I ran the script with these updates in an environment that simulates the scheduled github action and it worked as intended.

Decrease data pushed to socrata through api

---

dbt/models/open_data/open_data.vw_appeal.sql
dbt/models/open_data/open_data.vw_assessed_value.sql
dbt/models/open_data/open_data.vw_parcel_address.sql
dbt/models/open_data/open_data.vw_parcel_proximity.sql
dbt/models/open_data/open_data.vw_parcel_sale.sql
dbt/models/open_data/open_data.vw_parcel_status.sql
dbt/models/open_data/open_data.vw_parcel_universe_current.sql
dbt/models/open_data/open_data.vw_parcel_universe_historical.sql
dbt/models/open_data/open_data.vw_permit.sql
dbt/models/open_data/open_data.vw_property_tax_exempt_parcel.sql
dbt/models/open_data/open_data.vw_res_condo_unit_char.sql
dbt/models/open_data/open_data.vw_sf_mf_improvement_char.sql

We transform year columns from strings to numbers for each of the assets on the open data portal. Part of having the `open_data` Athena db is to have those views represent what's on the open data portal without any transformations being done there (Socrata). It stands to reason year fields in the Athena db should also be numbers.
Having year columns as strings in our Athena dbs is an artifact of partitioning by year, rather than any design choice on our part - I shouldn't have continued this practice in the `open_data` db when it isn't necessary there.

Change open data year columns type to INT

---

dbt/models/reporting/schema.yml

We've decided that this test is too sensitive to outliers due to the variance in pre-mailed values that are under active review. This PR disables the PRB bounds test for pre-mailed values, since we are putting together a provisional value dashboard that will expose stats like PRB to teams that are accountable to them in a more accessible way.

Disable PRB test for pre-mailed values

---

dbt/models/default/columns.md
dbt/models/default/default.vw_pin_permit.sql
dbt/models/default/schema/default.vw_pin_permit.yml
dbt/models/open_data/open_data.vw_permit.sql

Quick PR to add a municipality column to our permits views for easy filtering/aggregation. No rush to review this, just figured we'd have it ready to go if we decide we want to move forward with adding the column to the open data asset.
```
select
count(*) as count,
'new' as new
from z_ci_add_municipalities_to_permits_view_default.vw_pin_permit
union all
select
count(*) as count,
'old' as new
from default.vw_pin_permit
```
count | new
-- | --
554250 | old
554250 | new
```
select
year,
sum(cast(municipality is null as int)) as null_muni,
sum(cast(municipality is not null as int)) as non_null_muni
from z_ci_add_municipalities_to_permits_view_default.vw_pin_permit
where year between '1999' and '2025'
group by year
order by year desc
```
year | null_muni | non_null_muni
-- | -- | --
2025 | …

Add municipality to permit views

---

.github/scripts/test_open_data_assets.py

This PR addresses an issue with the permits view in Athena/asset on the open data portal. Because this dataset is the first we've had that can have `NULL`  year values, handling its year field can lead to difficulties we haven't encountered in the past. Specifically, the Socrata API won't return a year field at all for grouped queries where the group is `year = NULL`, and python's `sort` function cannot handle `NULL` values.
Additionally, this PR makes sure that the test script successfully links years from our Athena db that are typed as `int` to year fields from Socrata, which its API delivers as `string` regardless of being numbers.

Fix permit year field in open data asset tests

---

socrata/socrata_upload.py

This PR addresses two issues:
- In https://github.com/ccao-data/data-architecture/pull/788 I changed all of the open data views' `year` fields to `int` from `string` without anticipating how it would affect this script. It did, and it [caused our monthly upload to fail](https://github.com/ccao-data/data-architecture/actions/runs/14770244541/job/41469029211).
- The 'all' option for the `years` input was essentially being ignore by the script and is now properly handled
Successful run with `all` option invoked and handling `year` fields as `int` [here](https://github.com/ccao-data/data-architecture/actions/runs/14782947275/job/41505671868).

Address `year` field to `int` in `open_data` db

---

dbt/models/pinval/docs.md
dbt/models/pinval/schema.yml

I noticed while looking at our source freshness tests today that [dbt is throwing some warnings related to PINVAL tables](https://github.com/ccao-data/data-architecture/actions/runs/14837513125/job/41652085074#step:4:26). It looks like when we added these tables in https://github.com/ccao-data/data-architecture/pull/793, we used the incorrect table names and docs blocks names in the `schema.yml` configuration, which was causing dbt to not know about the tables. This PR fixes those errors to resolve the warnings and correct the DAG.
See [this workflow](https://github.com/ccao-data/data-architecture/actions/runs/14841942935/job/41666771867?pr=808#step:9:43) for evidence that the DAG builds correctly, with no warnings.

Fix PINVAL table configs

---

dbt/models/open_data/open_data.vw_permit.sql

Two columns that were removed from the Permits open data asset are still in the athena view that feeds it. There should be 22 columns in the view (21 that will show up on the open data portal + a row_id columns). This PR leaves us with 22 columns rather than 24. Output from an API update performing as expected can be found here.

Remove deprecated columns from permits open data view

---

dbt/models/pinval/pinval.vw_comp.sql

In https://github.com/ccao-data/model-res-avm/pull/360 we made some changes to the comps pipeline so that comps for 2-3 card parcels better reflect the way that we value these parcels as of https://github.com/ccao-data/model-res-avm/pull/328. This PR updates the `pinval.vw_comp` view to use the comp run from this PR as the basis for comps, so that we can start using fixed comps in PINVAL development.
Connects https://github.com/ccao-data/pinval/issues/41.

Use comp run with fixed small multicards in `pinval.vw_comp` view

---

dbt/models/default/default.vw_pin_appeal.sql
dbt/models/default/schema/default.vw_pin_appeal.yml
dbt/models/shared_columns.md

I went through an example of each column being `TRUE` to make sure it agreed with what appears in iasWorld, and it does.
@ccao-jardine @jeancochrane  while `TRUE` seems to indicate what you would assume, `FALSE` and `NULL` seem entirely interchangeable here. Do either of you have a preference for how to code NULL/FALSE? Should we just consider anything not `TRUE` as `FALSE`, or leave it as is? Case no. 24-74-1468720 is a good example. Only `reason_other` is `TRUE`, no other boxes are checked when you investigate in iasWorld, but for whatever reason `reason_lack_of_uniformity` is `FALSE`:
```
select case_no,
pin,
reason_lack_of_uniformity,
reason_fire_damage,
reason_building_no_longer_exists,
reason_over_valuation,
reason_property_description_error,
reason_vacancy_occupancy, …
```

Add filer "Reason for Appeal" to `default.vw_pin_appeal`

---

dbt/models/reporting/reporting.vw_assessment_roll_muni.sql

> The `reporting_vw_assessment_roll_muni_phase_av_share_range` test [is failing](https://github.com/ccao-data/data-architecture/actions/runs/15533165101/job/43726325919#step:7:625) for a group whose total AV is zero and whose AV share is `NaN`. I believe the zero AV causes a division-by-zero error in the calculation of the `phase_av_share` column, which in turn causes the `NaN` value, though I'm not totally confident in that assessment.
Correct. Problem is resolved with a `CASE WHEN` to avoid calculating a phase av share when there's no phase av.  Results of
```
select *
from z_ci_833_resolve_unexpected_nan_for_phase_av_share_in_vw_assessment_roll_muni_reporting.vw_assessment_roll_muni
where phase_av_share is null
```
[are attached](https://github.com/user-attachments/files/20679727/d8ab8b …

Resolve unexpected `NaN` for `phase_av_share` in `vw_assessment_roll_muni`

---

.github/actions/setup_dbt/action.yaml
.github/workflows/build_and_test_dbt.yaml
.github/workflows/build_daily_dbt_models.yaml
.github/workflows/cleanup_dbt_resources.yaml
.github/workflows/deploy_dbt_docs.yaml
.github/workflows/socrata_upload.yaml
.github/workflows/test_dbt_models.yaml
.github/workflows/test_dbt_source_freshness.yaml
.github/workflows/test_iasworld_data.yaml
.github/workflows/test_open_data_assets.yaml

This PR updates the `setup_dbt` composite action to add a [masks](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#masking-a-value-in-a-log) for sensitive AWS identifiers. This is a best practice to ensure that these sensitive identifiers never get accidentally printed to logs in the course of a dbt command or direct AWS CLI operation. All of our workflows that interact with AWS resources use the `setup_dbt` composite action, so by masking identifiers in the context of the action, we should get good coverage for protecting our logs.
See here for a log line showing the mask: https://github.com/ccao-data/data-architecture/actions/runs/15620684692/job/44004516960?pr=842#step:3:219

Mask sensitive AWS identifiers in GitHub workflow logs

---

etl/scripts-ccao-data-warehouse-us-east-1/spatial/spatial-school.R

@jeancochrane found two school districts with the same census geoids in `spatial.school`. Turns out I screwed up manually assigning geoids due to an incomplete join in the `spatial-school.R` warehouse script. Got the new geoid from tidycensus:
```
tidycensus::get_acs(
geography = "school district (elementary)",
table = "B01001",
survey = "acs5",
output = "wide",
state = "IL",
year = 2023,
cache_table = TRUE
)
```
Also found some random errors with the raw cps attendance data in 2011 that we were failing to address - one school number and one school name.
```
select geoid,
year,
count(*)
from spatial.school_district
where geoid is not null
group by geoid,
year
having count(*) > 1
```
shows we're good now.

Fix school district geoid

---

dbt/models/pinval/pinval.vw_assessment_card.sql

This PR updates `pinval.vw_assessment_card` to produce clean readable columns
- township name
- detailed class code
so we can bring them into the html doc for improved readability, based on this issue: https://github.com/ccao-data/pinval/issues/60

Add township_name and detailed class column for better user output

---

dbt/models/pinval/columns.md
dbt/models/pinval/docs.md
dbt/models/pinval/pinval.vw_assessment_card.sql
dbt/models/pinval/pinval.vw_comp.sql
dbt/models/pinval/schema.yml

This PR follows up on the changes we made to `pinval.vw_assessment_card` in https://github.com/ccao-data/data-architecture/pull/851 to add rows for every parcel in the County for every model run. That PR used a confusing convention of `parcel_*` and `model_*` column name prefixes for new columns in order to skirt around the problem that we select `*` from `model.assessment_card` and so can't rename any of its columns. This PR resolves this problem at the root by instead selecting the specific columns that we want from `model.assessment_card` such that we can filter them, rename them, or transform them.
Note that this choice introduces a maintenance burden, in that we have to manually add any new predictors to the set of selected columns in `pinval.vw_assessment_card` whenever we add new …

Simplify the `pinval.vw_assessment_card` data model

---

dbt/models/pinval/schema.yml

In https://github.com/ccao-data/pinval/pull/93, we're changing the PINVAL reports based on the assumption that report-eligible PINs will always have not-null card numbers (see in particular [this comment](https://github.com/ccao-data/pinval/pull/93/files#r2208624634)). This PR adds a data test to enforce that assumption so we will be notified if we ever break it.

Add `not_null` test for PINVAL card num field to support better char table UX

---

dbt/seeds/ccao/ccao.class_dict.csv

@ccao-jardine noticed a small typo in the class description for class 234 in the `ccao.class_dict` seed. This one-liner PR fixes that typo.

Fix typo in 234 class description in `ccao.class_dict` seed

---

dbt/scripts/export_models.py
dbt/scripts/utils/helpers.py

This PR adds a few suggestions on top of https://github.com/ccao-data/data-architecture/pull/860 to improve remote logging for the IC reference file export script. Python logging is annoying and confusing but I think with these changes we'll be in good shape.
See the log stream for today for the three example scenarios I tested (script completes successfully, script encounters an error with a message, script encounters an error without a message).

Simplify IC reference file logging config

---

etl/renv.lock

Just bumping `aws.s3`, `paws` and a few other minor package versions to avoid the annoying `get_bucket_df` error we've gotten in the past.

Bump AWS R deps in etl

---

dbt/models/model/schema.yml

Similar to https://github.com/ccao-data/data-architecture/pull/885, the `model_assessment_card_meta_card_num_not_null` test [is failing again](https://github.com/ccao-data/data-architecture/actions/runs/17375666797/job/49321314303#step:7:674) because we ran two new model runs on prior years whose assessment sets contained parcels with missing cards. This PR bumps that threshold... again.
This test relies on the assumption that we won't run models on old assessment years; that assumption has generally been true since the introduction of this test, but in recent weeks we've initiated a spike in model development that has broken the assumption. I'm wondering if there's a better way to approach this test, though I don't have any ideas that I would consider to be a slam dunk.
My best idea is …

Bump threshold for not-null test on `model.assessment_card.meta_card_num`

---

.github/workflows/build_and_test_dbt.yaml

Today we encountered an issue where a PR altered a table that was associated with a lot of intensive tests, so when a team member pushed a number of commits to that PR in rapid succession, the cumulative `build-and-test-dbt` workflows for each of those commits queued a huge number of queries in total and caused Athena to crash. This PR implements a quick way of reducing the impact of that situation by limiting the number of concurrent builds that we allow for the `build-and-test-dbt` workflow to one per branch, and configuring PRs so that they cancel outdated builds when new ones come in. (For pushes to the main branch, we queue new builds instead of canceling old ones.)
This is not the most sophisticated or effective way of resolving the query load problem because the `dbt-athena` plugin …

Limit concurrent dbt builds to one per branch on CI

---

etl/scripts-ccao-data-raw-us-east-1/spatial/spatial-economy.R
etl/scripts-ccao-data-warehouse-us-east-1/spatial/spatial-economy.R

Our current enterprise zone data is not what the [city of chicago makes available](https://data.cityofchicago.org/Community-Economic-Development/Boundaries-Enterprise-Zones/64xf-pyvh). Our ingest of the data we have is undocumented and our data seems to be industrial growth zones (which we already have separately) rather than enterprise zones. This PR fixes this by pointing our `spatial-economy` ingest script to the city of chicago's data and then updating the relevant warehouse script to correctly process the new shapefile.
Once these updates and the new data has been reviewed I will trigger glue crawlers and rebuilds in dbt.
Cleaned version of new data can be inspected from `etl` using `geoarrow::read_geoparquet_sf("s3://ccao-data-warehouse-us-east-1/spatial/economy/enterprise_zone/year= …

Fix enterprise zone ingest
